--
-- PostgreSQL database dump
--

\restrict 7CwN5NNDHhdZ8dTBtF7h9RPgzUOM5hPDmrQmpR2kfldeasnBhtfOV09YUe5NVND

-- Dumped from database version 15.18
-- Dumped by pg_dump version 15.18

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: matches; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.matches (
    id integer NOT NULL,
    file_origin character varying NOT NULL,
    match_date date,
    season character varying,
    home_team_id integer,
    away_team_id integer
);


ALTER TABLE public.matches OWNER TO postgres;

--
-- Name: matches_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.matches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: player_match_stats; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.player_match_stats (
    id integer NOT NULL,
    match_id integer NOT NULL,
    jersey integer,
    player_name character varying,
    team_played_for_id integer,
    is_libero boolean,
    points_total integer,
    points_break integer,
    plus_minus integer,
    service_total integer,
    service_errors integer,
    service_aces integer,
    total_receptions integer,
    reception_errors integer,
    positive_receptions integer,
    excellent_receptions integer,
    attack_total integer,
    attack_errors integer,
    attack_blocked integer,
    attack_kills integer,
    block_points integer
);


ALTER TABLE public.player_match_stats OWNER TO postgres;

--
-- Name: player_match_stats_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.player_match_stats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.player_match_stats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teams; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teams (
    id integer NOT NULL,
    team_name character varying NOT NULL
);


ALTER TABLE public.teams OWNER TO postgres;

--
-- Name: teams_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.teams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: matches; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.matches (id, file_origin, match_date, season, home_team_id, away_team_id) FROM stdin;
1	match_reports/match_4ba567b9-b6c7-455b-b8ff-73b061ac2213.pdf	2026-01-24	2025/2026	1	2
2	match_reports/match_30ecad89-f7af-419a-b3d6-e9d958bbddde.pdf	2025-10-04	2025/2026	2	3
3	match_reports/match_934d0d7a-5dad-4a91-9adb-5a04966ed0be.pdf	2026-02-08	2025/2026	4	5
4	match_reports/match_e50aa9b5-019c-47dd-a55d-fd49012fc227.pdf	2025-10-26	2025/2026	6	5
5	match_reports/match_d0fea0ad-7e96-475e-922a-3987ddbb4d73.pdf	2026-01-11	2025/2026	6	2
6	match_reports/match_d6d7bc9c-b8f7-4136-b856-fef86be53ac7.pdf	2025-10-13	2025/2026	3	1
7	match_reports/match_935f2493-4100-466e-b2fd-d81928fe4146.pdf	2026-01-11	2025/2026	3	5
8	match_reports/match_d63da4eb-93ac-4142-ac71-990f06952d1e.pdf	2025-10-26	2025/2026	3	4
9	match_reports/match_1c781c25-78ca-45db-aee9-ae46fa03cfc1.pdf	2025-11-29	2025/2026	5	4
10	match_reports/match_7e2a2a2f-242e-4b5c-98c9-9952d501550d.pdf	2026-02-01	2025/2026	6	7
11	match_reports/match_accff988-8c75-4604-806b-422ed18d2241.pdf	2026-02-01	2025/2026	4	2
12	match_reports/match_4f1dc849-0941-4e4f-9888-4eadebffdacc.pdf	2026-02-07	2025/2026	1	6
13	match_reports/match_58dce57a-5606-4c60-991e-4dc85ebe0556.pdf	2026-01-17	2025/2026	4	3
14	match_reports/match_6d251c6d-6680-4dea-ba1c-85c37679276e.pdf	2026-01-10	2025/2026	1	4
15	match_reports/match_8f537b24-397f-4bf9-864d-c87f0555f680.pdf	2025-12-13	2025/2026	8	6
16	match_reports/match_8ac3623f-1e7d-4352-a2dc-172c46c891a0.pdf	2025-11-22	2025/2026	2	4
17	match_reports/match_303af715-83c1-42e9-b3cd-8a35d07ee798.pdf	2025-12-13	2025/2026	1	3
18	match_reports/match_dfbb7232-d2bb-4045-9649-4c9e919a8dd6.pdf	2026-02-02	2025/2026	3	8
19	match_reports/match_aa5d87d3-c058-4c0c-87df-6fa3a12ef2c5.pdf	2025-10-04	2025/2026	1	7
20	match_reports/match_46037d1a-aaac-4529-8ee5-e334f7577679.pdf	2026-02-04	2025/2026	7	8
21	match_reports/match_414c119a-0ecf-4e6f-a27c-be99d8a8784d.pdf	2025-11-30	2025/2026	3	7
22	match_reports/match_d89e9c3e-2a0a-4d09-b930-96cd18ad6ffa.pdf	2025-11-15	2025/2026	8	4
23	match_reports/match_97b9e724-2d02-425d-9643-c872a66c2602.pdf	2026-01-17	2025/2026	5	6
24	match_reports/match_ff63b4f9-07c1-4c0d-84f9-111fc1e65098.pdf	2026-01-24	2025/2026	7	5
25	match_reports/match_4b76b51f-0886-42cd-8d6c-105f34a09a29.pdf	2025-11-22	2025/2026	8	3
26	match_reports/match_8fbf0edf-4b29-4c8a-8d77-9f705cc45c3f.pdf	2025-12-14	2025/2026	2	5
27	match_reports/match_653e8509-2e5b-4b02-a34e-ced9d48312f0.pdf	2025-11-15	2025/2026	2	1
28	match_reports/match_1378c6c7-e734-47eb-8c36-f6197e675794.pdf	2025-10-05	2025/2026	8	5
29	match_reports/match_5491c233-e329-48db-bd7a-7a9e9b485b44.pdf	2025-11-22	2025/2026	1	5
30	match_reports/match_d707e928-254b-4a41-9ff4-42b332ffcc8c.pdf	2026-01-31	2025/2026	5	1
31	match_reports/match_c0123599-61b9-4396-ad73-4ec1b1371465.pdf	2025-12-06	2025/2026	5	8
32	match_reports/match_f7fb2c69-c509-4a0c-999f-d298a16562be.pdf	2026-01-18	2025/2026	2	7
33	match_reports/match_0d45f270-d458-497d-ab93-3e301d17949d.pdf	2026-02-07	2025/2026	8	2
34	match_reports/match_0a97949f-d713-4e7c-bd6e-9f506a1794b4.pdf	2026-02-07	2025/2026	7	3
35	match_reports/match_85a8bc02-11b2-4a6f-9295-6f4db0ccb46d.pdf	2025-10-05	2025/2026	4	6
36	match_reports/match_be23a034-0d51-4c98-bc4f-7c5943419620.pdf	2025-10-11	2025/2026	7	4
37	match_reports/match_ddd0789a-a4ed-4475-9013-e0ce01546016.pdf	2025-10-18	2025/2026	2	6
38	match_reports/match_56b66715-9c32-4fc2-a3b1-a18c2b48328d.pdf	2025-12-29	2025/2026	2	8
39	match_reports/match_1dc0ff2e-22ae-41a9-8593-1b948fddadff.pdf	2025-10-18	2025/2026	8	7
40	match_reports/match_ff845bcb-1656-4339-9813-bb8d99e5c623.pdf	2025-11-16	2025/2026	6	3
41	match_reports/match_38c0aa81-745a-4a00-a0fb-f53af3e27c35.pdf	2025-12-06	2025/2026	7	1
42	match_reports/match_f7bf15fb-988e-4efe-8016-6ea571eae078.pdf	2025-10-25	2025/2026	1	8
43	match_reports/match_0f4c3acc-ce3f-4414-86de-d00330aa7a12.pdf	2025-10-19	2025/2026	4	1
44	match_reports/match_6af6ab7a-9c18-4617-a847-1ef54b63283d.pdf	2025-11-22	2025/2026	7	6
45	match_reports/match_e5f3ebba-7097-4130-8c78-0bbee06cb99c.pdf	2025-10-25	2025/2026	7	2
46	match_reports/match_76e7d043-af13-4087-8313-cbe727a99f56.pdf	2025-10-11	2025/2026	6	8
47	match_reports/match_383bc151-f1ad-4876-8d8d-519778525017.pdf	2025-12-07	2025/2026	3	2
48	match_reports/match_8de77a4b-30bb-4a12-b1cd-14558231c2d3.pdf	2025-11-16	2025/2026	5	7
49	match_reports/match_17f02183-a9b7-44c2-ad56-e7b427fd46e0.pdf	2025-10-19	2025/2026	5	3
50	match_reports/match_48d0a14d-b64e-4178-91e2-7ca5da92f85d.pdf	2025-10-11	2025/2026	5	2
51	match_reports/match_819673c0-978e-48a7-8d85-6c5f3e41f4b4.pdf	2026-01-24	2025/2026	4	8
52	match_reports/match_cac5a016-e98e-47bf-87e3-f8b56a197824.pdf	2026-01-17	2025/2026	8	1
53	match_reports/match_c9af010f-9d52-4ae0-b9d1-d9f90cac66e4.pdf	2025-12-15	2025/2026	4	7
54	match_reports/match_68df03af-0918-4dc5-a3d6-3a57723d2aef.pdf	2025-12-07	2025/2026	6	4
55	match_reports/match_27bf502e-8d0b-4c5c-af91-6bd65e687b5a.pdf	2026-01-25	2025/2026	3	6
56	match_reports/match_a8595dc7-f1fd-4bf4-81b5-1854a0d9e733.pdf	2025-11-30	2025/2026	6	1
\.


--
-- Data for Name: player_match_stats; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.player_match_stats (id, match_id, jersey, player_name, team_played_for_id, is_libero, points_total, points_break, plus_minus, service_total, service_errors, service_aces, total_receptions, reception_errors, positive_receptions, excellent_receptions, attack_total, attack_errors, attack_blocked, attack_kills, block_points) FROM stdin;
1	1	2	BIVER Antoine	1	f	2	0	0	6	0	0	1	0	0	0	5	1	1	2	0
2	1	3	WAGNER Victor	1	f	1	0	1	7	0	0	0	0	0	0	2	0	0	1	0
3	1	5	SOMMERHALTER Vince	1	f	1	0	-6	2	1	0	13	6	3	2	3	0	0	1	0
4	1	6	BARTH Frederic	1	t	0	0	-5	0	0	0	19	5	7	4	0	0	0	0	0
5	1	10	HOFFMANN Maxime	1	f	3	2	3	7	0	1	0	0	0	0	6	0	0	2	0
6	1	13	FELLINGER Felix	1	f	3	0	-5	7	3	0	0	0	0	0	20	3	2	3	0
7	1	15	VOSAHLO Frantisek	1	f	4	1	0	3	0	0	4	2	1	1	9	1	1	4	0
8	1	18	PEREIRA Loic	1	f	0	0	-1	1	0	0	1	0	0	0	1	0	1	0	0
9	1	28	DARROSA JANKOVIC Ni	1	f	6	0	-5	6	2	0	24	3	7	3	16	3	3	6	0
10	1	1	AUZANI Leonardo	2	f	5	4	4	6	1	0	0	0	0	0	1	0	0	1	4
11	1	2	MARINHO NOVAIS Sam	2	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
12	1	3	CALHOUN Cameron	2	f	7	4	1	8	3	2	11	1	4	2	9	2	0	5	0
13	1	4	MARINHO NOVAIS Sim	2	f	6	5	5	18	1	5	0	0	0	0	2	0	0	1	0
14	1	5	MAGGIOLO Enzo	2	f	20	6	16	7	3	0	0	0	0	0	22	1	0	19	1
15	1	6	BRAAS Gilles	2	f	1	0	1	1	0	0	0	0	0	0	1	0	0	1	0
16	1	7	MILOSEVIC Boris	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
17	1	8	MATILDE DA LUZ Ryan	2	f	7	5	5	13	2	2	0	0	0	0	4	0	0	3	2
18	1	10	ARAB Sina	2	f	5	2	5	5	0	0	5	0	2	2	10	0	0	5	0
19	1	14	HALDORSEN Jan	2	f	4	3	3	10	0	2	0	0	0	0	2	1	0	1	1
20	1	15	GAJIN Mareja	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
21	1	17	TOPALOV Todor	2	f	5	3	2	6	2	0	12	0	4	4	14	1	0	5	0
22	1	23	GARBO Lorenzo	2	t	0	0	0	0	0	0	5	0	2	2	0	0	0	0	0
23	2	2	MARINHO NOVAIS Sam	2	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
24	2	3	CALHOUN Cameron	2	f	4	1	-1	4	2	0	0	0	0	0	8	1	2	4	0
25	2	4	MARINHO NOVAIS Sim	2	f	0	0	0	5	0	0	0	0	0	0	1	0	0	0	1
26	2	5	MAGGIOLO Enzo	2	f	9	3	6	6	2	0	0	0	0	0	11	0	1	9	0
27	2	6	BRAAS Gilles	2	f	3	3	2	8	1	0	1	0	0	0	1	0	0	1	2
28	2	7	MILOSEVIC Boris	2	f	3	2	2	7	1	0	4	0	1	1	5	0	0	3	0
29	2	9	INEMEK Louis	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
30	2	10	ARAB Sina	2	f	7	3	6	13	0	0	8	1	4	3	7	0	0	5	2
31	2	13	CZAPOR Leon Eric	2	f	2	0	1	0	0	0	0	0	0	0	4	0	1	2	0
32	2	16	AUZANI Leonardo	2	f	6	4	3	9	1	0	1	1	0	0	7	0	1	3	3
33	2	17	TOPALOV Todor	2	f	12	5	5	11	2	2	8	2	3	2	17	3	0	10	0
34	2	19	HALDORSEN Jan	2	f	3	0	3	10	0	0	0	0	0	0	4	0	0	3	0
35	2	23	GARBO Lorenzo	2	t	0	0	0	0	0	0	14	0	10	9	0	0	0	0	0
36	2	1	SPEIDEL Karim	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
37	2	5	SANTER Philippe	3	f	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0
38	2	7	NEME RODRIGUES Nad	3	f	2	0	-2	7	2	0	1	0	0	0	9	1	1	2	0
39	2	8	BOLLENDORFF Pol	3	f	9	1	5	8	1	0	8	0	5	3	19	0	3	7	2
40	2	9	HIRTZ WEIS Sam	3	f	3	1	-3	4	1	0	5	2	2	1	7	2	1	3	0
41	2	10	ZENDER Christophe	3	f	3	1	1	4	0	0	8	0	3	3	13	2	0	3	1
42	2	12	SINDECUSE Noah	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
43	2	14	WILDGEN Charel	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
44	2	17	DA SILVA MARQUES Ma	3	t	0	0	0	0	0	0	16	0	10	4	0	0	0	0	0
45	2	18	OESCH Noah	3	f	4	1	-8	8	3	0	8	1	1	1	19	6	2	2	2
46	2	19	DIAS AMORIM Daniel	3	f	0	0	-2	2	0	0	9	1	2	2	2	0	1	0	0
47	2	20	BUSSHUVEN Tim	3	f	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0
48	2	23	STEIN Max	3	t	0	0	-3	0	0	0	9	3	0	0	0	0	0	0	0
49	2	44	MAZUR Marcel	3	f	6	2	2	9	1	2	0	0	0	0	9	3	0	4	0
50	3	1	HONORATO DE ALMEID	4	f	4	1	3	17	0	0	0	0	0	0	6	1	0	3	1
51	3	2	CAVALCANTI DE OLIVEI	4	f	2	2	1	13	1	2	0	0	0	0	2	0	0	0	0
52	3	3	MADEJ Maciej	4	f	3	0	2	2	0	0	0	0	0	0	6	1	0	3	0
53	3	4	MARECHAL Adrien	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
54	3	5	LOYOLA LAVIN Nelson	4	f	0	0	0	1	0	0	0	0	0	0	1	0	0	0	0
55	3	6	GARCIA Pedro	4	f	10	4	5	6	2	1	0	0	0	0	15	2	1	8	1
56	3	11	MANGEN Tim	4	f	10	8	9	11	0	3	0	0	0	0	7	1	0	5	2
57	3	12	MEYERS Dan	4	f	0	0	-1	2	1	0	0	0	0	0	0	0	0	0	0
58	3	13	MARECHAL Yann	4	f	0	0	0	0	0	0	1	0	1	0	1	0	0	0	0
59	3	14	MICHOTTE Arthur	4	f	15	13	5	8	3	1	19	3	5	4	20	1	3	10	4
60	3	16	MADEJ Jakub	4	t	0	0	-1	0	0	0	4	1	1	0	0	0	0	0	0
61	3	18	MARETTE William	4	t	0	0	0	0	0	0	10	0	6	5	0	0	0	0	0
62	3	19	HUKEL Jakub	4	f	14	7	10	13	2	3	8	0	6	6	18	1	1	11	0
63	3	1	DEINEGA Vladimir	5	f	5	0	-6	7	1	0	14	6	2	1	16	1	3	5	0
64	3	3	DOBRE Sebastian	5	f	0	0	-1	11	1	0	0	0	0	0	1	0	0	0	0
65	3	4	MARINKOVIC Luka	5	f	11	5	4	11	5	2	2	1	0	0	14	0	1	8	1
66	3	8	BILAN Filip	5	f	3	0	-3	7	1	0	0	0	0	0	18	2	3	2	1
67	3	10	POLFER Felix	5	f	1	0	1	3	0	0	3	0	1	0	2	0	0	1	0
68	3	12	CONSTANTINOU Michai	5	f	1	0	-5	4	1	0	19	4	5	4	8	0	1	1	0
69	3	22	BRISBOIS Nicolas	5	t	0	0	-1	0	0	0	16	1	6	6	0	0	0	0	0
70	3	24	HAJ ISMAIL Mohamed	5	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
71	3	27	COURRIOUX Quentin	5	f	1	0	-3	3	0	0	10	3	2	0	5	1	0	1	0
72	3	77	DUDA Karol	5	f	8	2	8	5	0	0	0	0	0	0	8	0	0	6	3
73	3	82	LOMACZ Jakub	5	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
74	4	1	WOLLES Sam	6	f	1	0	-12	9	0	0	17	5	7	7	13	5	3	1	0
75	4	3	HINKEL Sam	6	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
76	4	5	EVEN Philippe	6	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
77	4	6	ENGELDINGER Tom	6	f	6	2	1	6	1	0	0	0	0	0	12	1	3	4	2
78	4	7	SZTURMA Nicolas	6	f	8	0	4	10	0	0	20	2	6	4	15	1	1	8	0
79	4	9	WIRTZ Sam	6	f	7	1	1	9	2	0	0	0	0	0	21	3	1	6	1
80	4	10	THIES Joey	6	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
81	4	11	HONG Joseph	6	f	0	0	0	0	0	0	0	0	0	0	1	0	0	0	0
82	4	18	DZINIC Aziz	6	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
83	4	19	BOLLENDORFF Frank	6	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
84	4	55	WEIRIG Yann	6	f	6	2	4	9	1	0	0	0	0	0	8	1	0	5	1
85	4	69	BESCH Tim	6	t	0	0	-5	0	0	0	28	5	9	4	0	0	0	0	0
86	4	77	BETTI Raphael	6	f	2	1	0	7	0	0	0	0	0	0	4	1	1	1	1
87	4	1	DEINEGA Vladimir	5	f	16	4	12	12	0	0	5	0	2	2	25	2	2	13	3
88	4	3	DOBRE Sebastian	5	f	3	3	1	12	1	1	0	0	0	0	3	0	1	1	1
89	4	4	MIRINKOVIC Luka	5	f	9	4	6	15	3	4	0	0	0	0	8	0	0	5	0
90	4	8	BILAN Filip	5	f	3	1	1	6	1	0	0	0	0	0	4	1	0	3	0
91	4	9	VUJOVIC Pavle	5	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
92	4	12	CONSTANTINOU Michai	5	f	10	5	6	12	0	2	18	0	4	2	16	4	0	7	1
93	4	17	POLFER Felix	5	t	0	0	0	0	0	0	12	0	0	0	0	0	0	0	0
94	4	24	HAJ ISMAIL Mohamed	5	f	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0
95	4	77	DUDA Karol	5	f	6	3	3	6	1	0	0	0	0	0	7	2	0	3	3
96	4	82	LOMACZ Jakub	5	f	11	5	7	9	2	0	11	0	4	2	16	0	2	10	1
97	5	1	WOLLES Sam	6	f	2	0	-7	6	0	0	12	2	5	4	19	1	6	2	0
98	5	3	HINKEL Sam	6	f	2	0	0	3	0	0	0	0	0	0	7	2	0	2	0
99	5	5	EVEN Philippe	6	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
100	5	6	ENGELDINGER Tom	6	f	6	3	1	11	2	3	1	1	0	0	8	1	1	2	1
101	5	7	SZTURMA Nicolas	6	f	3	2	-2	2	0	0	3	0	1	0	15	3	2	3	0
102	5	10	THIES Joey	6	t	0	0	-2	0	0	0	15	2	6	2	0	0	0	0	0
103	5	11	HONG Joseph	6	f	0	0	-1	2	1	0	1	0	0	0	0	0	0	0	0
104	5	18	DZINIC Aziz	6	f	3	1	2	3	1	0	0	0	0	0	4	0	0	2	1
105	5	19	BOLLENDORFF Frank	6	f	2	0	0	2	0	0	0	0	0	0	4	0	2	2	0
106	5	55	WEIRIG Yann	6	f	2	1	-2	3	2	0	0	0	0	0	6	1	1	1	1
107	5	69	BESCH Tim	6	f	2	0	-5	4	0	0	31	2	14	9	11	2	3	2	0
108	5	77	BETTI Raphael	6	f	2	0	2	4	0	0	2	0	0	0	5	0	0	1	1
109	5	1	AUZANI Leonardo	2	f	9	4	7	11	1	1	0	0	0	0	10	1	0	7	1
110	5	2	MARINHO NOVAIS Sam	2	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
111	5	3	CALHOUN Cameron	2	f	14	11	13	5	0	0	0	0	0	0	15	0	1	8	6
112	5	4	MARINHO NOVAIS Sim	2	f	2	2	2	7	0	0	0	0	0	0	1	0	0	1	1
113	5	5	MAGGIOLO Enzo	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
114	5	6	BRAAS Gilles	2	f	0	0	-2	4	1	0	0	0	0	0	1	1	0	0	0
115	5	7	MILOSEVIC Boris	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
116	5	8	MATILDE DA LUZ Ryan	2	f	5	2	4	4	0	0	0	0	0	0	4	1	0	2	3
117	5	10	ARAB Sina	2	f	7	5	4	28	2	2	11	1	7	4	9	0	0	5	0
118	5	13	CZAPOR Leon Eric	2	f	0	0	-1	0	0	0	1	0	0	0	1	1	0	0	0
119	5	14	HALDORSEN Jan	2	f	3	1	1	2	2	0	0	0	0	0	3	0	0	3	0
120	5	15	GAJIN Mareja	2	f	3	2	3	7	0	0	0	0	0	0	5	0	0	1	2
121	5	17	TOPALOV Todor	2	f	12	6	3	6	3	0	5	1	0	0	22	2	3	10	2
122	5	23	GARBO Lorenzo	2	t	0	0	-3	0	0	0	17	3	9	5	0	0	0	0	0
123	6	1	SPEIDEL Karim	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
124	6	4	METZGER Loris	3	f	0	0	-1	4	1	0	13	0	6	3	3	0	0	0	0
125	6	5	SANTER Philippe	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
126	6	6	ZENDER Christophe	3	f	7	4	2	9	2	0	23	1	7	4	16	2	0	7	0
127	6	7	NEME RODRIGUES Nad	3	f	15	7	14	13	0	0	0	0	0	0	18	1	0	14	1
128	6	8	BOLLENDORFF Pol	3	f	15	3	11	21	0	0	7	1	3	1	28	2	1	14	1
129	6	9	HIRTZ WEIS Sam	3	f	7	4	4	11	2	0	1	0	0	0	9	1	0	5	2
130	6	14	WILDGEN Charel	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
131	6	17	DA SILVA MARQUES Ma	3	t	0	0	-2	0	0	0	20	2	12	6	0	0	0	0	0
132	6	18	OESCH Noah	3	f	9	7	2	20	3	2	0	0	0	0	17	3	1	4	3
133	6	19	DIAS AMORIM Daniel	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
134	6	23	STEIN Max	3	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
135	6	44	MAZUR Marcel	3	f	7	5	1	13	3	1	0	0	0	0	8	2	1	2	4
136	6	1	NIZARD Gil	1	f	7	2	-6	13	2	1	25	1	13	10	27	4	6	6	0
137	6	3	WAGNER Victor	1	f	0	0	-1	3	1	0	0	0	0	0	1	0	0	0	0
138	6	5	SOMMERHALTER Vince	1	f	1	0	-2	2	1	0	6	2	2	2	1	0	0	1	0
139	6	7	FELLINGER Felix	1	f	11	4	7	7	2	1	1	0	0	0	19	0	2	9	1
140	6	10	HOFFMANN Maxime	1	f	10	2	8	9	1	0	0	0	0	0	14	1	0	9	1
141	6	15	BIVER Antoine	1	f	3	1	-1	15	1	0	0	0	0	0	10	2	1	3	0
142	6	17	BLANCO Juan Carlos	1	f	3	2	1	13	2	1	0	0	0	0	2	0	0	1	1
143	6	28	DARROSA JANKOVIC Ni	1	f	3	1	1	5	1	1	0	0	0	0	6	1	0	2	0
144	6	51	SANTOSI Peter	1	f	10	4	1	9	1	0	23	0	9	6	27	6	2	10	0
145	6	58	BARTH Frederic	1	t	0	0	0	0	0	0	25	0	13	9	0	0	0	0	0
146	7	1	SPEIDEL Karim	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
147	7	7	NEME RODRIGUES Nad	3	f	10	3	7	19	0	0	0	0	0	0	17	1	2	8	2
148	7	8	BOLLENDORFF Pol	3	f	14	6	-2	24	3	1	30	8	7	5	29	3	2	12	1
149	7	9	HIRTZ WEIS Sam	3	f	9	4	4	17	4	0	1	0	0	0	6	0	1	3	6
150	7	11	RZYMIANSKI Radoslaw	3	f	11	3	0	17	3	0	31	2	14	8	27	3	3	10	1
151	7	12	SINDECUSE Noah	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
152	7	14	WILDGEN Charel	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
153	7	17	DA SILVA MARQUES Ma	3	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
154	7	18	OESCH Noah	3	f	23	4	9	17	3	0	0	0	0	0	44	6	5	20	3
155	7	23	STEIN Max	3	t	0	0	-4	0	0	0	30	4	10	4	0	0	0	0	0
156	7	44	MAZUR Marcel	3	f	7	6	2	14	4	1	0	0	0	0	6	1	0	2	4
157	7	1	DEINEGA Vladimir	5	f	15	4	5	19	2	1	1	0	0	0	33	6	2	13	1
158	7	3	DOBRE Sebastian	5	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
159	7	4	MIRINKOVIC Luka	5	f	17	8	11	23	2	4	0	0	0	0	21	0	4	10	3
160	7	9	VUJOVIC Pavle	5	f	4	2	1	17	3	1	0	0	0	0	5	0	0	2	1
161	7	10	POLFER Felix	5	f	0	0	-2	1	1	0	1	1	0	0	0	0	0	0	0
162	7	12	CONSTANTINOU Michai	5	f	13	5	-6	14	6	0	41	6	20	12	28	3	4	10	4
163	7	22	BRISBOIS Nicolas	5	t	0	0	-4	0	0	0	30	4	12	8	0	0	0	0	0
164	7	24	HAJ ISMAIL Mohamed	5	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
165	7	77	DUDA Karol	5	f	11	4	8	14	1	0	0	0	0	0	16	0	2	8	3
166	7	82	LOMACZ Jakub	5	f	13	6	-2	23	3	2	18	2	11	5	24	5	5	10	1
167	8	1	SPEIDEL Karim	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
168	8	4	METZGER Loris	3	f	3	1	0	6	1	0	15	0	5	2	6	2	0	1	2
169	8	6	ZENDER Christophe	3	f	2	0	0	3	0	0	8	0	6	2	9	1	1	2	0
170	8	7	NEME RODRIGUES Nad	3	f	8	1	6	10	1	0	1	0	0	0	13	0	1	7	1
171	8	8	BOLLENDORFF Pol	3	f	13	4	4	9	2	0	24	3	2	2	23	1	3	11	2
172	8	9	HIRTZ WEIS Sam	3	f	4	3	0	8	3	1	0	0	0	0	5	0	1	1	2
173	8	12	SINDECUSE Noah	3	f	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0
174	8	17	DA SILVA MARQUES Ma	3	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
175	8	18	OESCH Noah	3	f	5	1	-3	6	3	0	0	0	0	0	17	2	3	5	0
176	8	19	DIAS AMORIM Daniel	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
177	8	20	BUSSHUVEN Tim	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
178	8	23	STEIN Max	3	t	0	0	-3	0	0	0	17	3	5	3	0	0	0	0	0
179	8	44	MAZUR Marcel	3	f	2	2	-3	12	4	2	0	0	0	0	2	0	1	0	0
180	8	1	HONORATO DE ALMEID	4	f	7	5	6	15	1	0	1	0	0	0	5	0	0	3	4
181	8	2	CAVALCANTI DE OLIVEI	4	f	1	1	1	17	0	1	0	0	0	0	0	0	0	0	0
182	8	3	MADEJ Maciej	4	f	7	4	5	2	1	0	0	0	0	0	9	0	1	7	0
183	8	4	MARECHAL Adrien	4	f	8	3	7	9	1	0	0	0	0	0	10	0	0	6	2
184	8	5	LOYOLA LAVIN Nelson	4	f	11	4	5	9	1	0	9	2	2	1	17	3	0	8	3
185	8	6	GARCIA Pedro	4	f	6	2	0	5	2	0	0	0	0	0	14	0	4	6	0
186	8	7	CLEES Jules	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
187	8	8	HEIRENS Sony	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
188	8	11	MANGEN Tim	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
189	8	13	MARECHAL Yann	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
190	8	14	MICHOTTE Arthur	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
191	8	16	MADEJ Jakub	4	t	0	0	-1	0	0	0	18	1	8	6	0	0	0	0	0
192	8	18	MARETTE William	4	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
193	8	19	HUKEL Jakub	4	f	11	6	4	16	2	2	13	0	7	2	18	3	2	8	1
194	9	1	DEINEGA Vladimir	5	f	12	3	4	9	2	0	18	0	9	9	26	2	4	10	2
195	9	3	DOBRE Sebastian	5	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
196	9	8	BILAN Filip	5	f	8	3	0	11	2	0	0	0	0	0	18	3	3	7	2
197	9	9	VUJOVIC Pavle	5	f	0	0	-2	10	2	0	0	0	0	0	1	0	0	0	0
198	9	12	CONSTANTINOU Michai	5	f	6	4	3	12	1	2	2	0	0	0	9	0	2	3	1
199	9	17	POLFER Felix	5	t	0	0	-2	0	0	0	26	2	10	6	0	0	0	0	0
200	9	23	QUINTUS Sam	5	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
201	9	24	HAJ ISMAIL Mohamed	5	f	0	0	0	3	0	0	0	0	0	0	0	0	0	0	0
202	9	27	COURRIOUX Quentin	5	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
203	9	77	DUDA Karol	5	f	3	2	1	4	1	0	0	0	0	0	2	1	0	0	3
204	9	82	LOMACZ Jakub	5	f	9	0	4	14	3	0	15	1	4	3	17	1	0	9	0
205	9	1	HONORATO DE ALMEID	4	f	9	7	9	12	0	0	2	0	2	1	8	0	0	5	4
206	9	2	CAVALCANTI DE OLIVEI	4	f	2	2	1	17	1	0	1	0	0	0	2	0	0	1	1
207	9	3	MADEJ Maciej	4	f	4	1	1	2	1	0	5	1	3	1	6	0	1	4	0
208	9	4	MARECHAL Adrien	4	f	8	3	5	12	2	0	1	1	0	0	10	0	0	6	2
209	9	5	LOYOLA LAVIN Nelson	4	f	10	3	6	9	1	0	15	1	6	3	15	0	2	9	1
210	9	6	GARCIA Pedro	4	f	10	4	-2	10	3	0	0	0	0	0	23	4	5	10	0
211	9	7	CLEES Jules	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
212	9	8	HEIRENS Sony	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
213	9	11	MANGEN Tim	4	f	0	0	-1	2	1	0	0	0	0	0	1	0	0	0	0
214	9	13	MARECHAL Yann	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
215	9	14	MICHOTTE Arthur	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
216	9	16	MADEJ Jakub	4	t	0	0	-1	0	0	0	15	1	9	2	0	0	0	0	0
217	9	18	MARETTE William	4	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
218	9	19	HUKEL Jakub	4	f	11	3	1	9	3	0	13	2	5	4	18	5	0	10	1
219	10	3	HINKEL Sam	6	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
220	10	5	EVEN Philippe	6	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
221	10	6	ENGELDINGER Tom	6	f	6	5	3	16	3	3	0	0	0	0	10	0	0	1	2
222	10	7	SZTURMA Nicolas	6	f	6	4	-6	12	0	1	22	6	6	4	26	3	3	4	1
223	10	11	HONG Joseph	6	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
224	10	18	DZINIC Aziz	6	f	10	4	-2	7	0	0	24	7	9	5	22	1	4	9	1
225	10	19	BOLLENDORFF Frank	6	f	11	3	6	6	0	0	1	0	0	0	20	1	4	11	0
226	10	55	WEIRIG Yann	6	f	9	6	7	10	1	0	0	0	0	0	12	1	0	7	2
227	10	69	BESCH Tim	6	t	0	0	-2	0	0	0	20	2	6	2	0	0	0	0	0
228	10	77	BETTI Raphael	6	f	4	1	2	9	1	0	0	0	0	0	8	1	0	4	0
229	10	1	SCHUBERT Jared	7	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
230	10	2	KOLACNY Jaromir	7	f	18	8	15	13	0	0	0	0	0	0	26	1	2	15	3
231	10	4	KIFFER Max	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
232	10	5	LANDUYDT Olivier	7	f	4	1	3	7	0	0	0	0	0	0	5	1	0	3	1
233	10	8	VARGAS Lyndon	7	f	7	3	6	11	0	0	0	0	0	0	8	0	1	5	2
234	10	11	HILBERT Colin	7	f	6	5	1	8	1	2	9	2	3	2	9	1	1	4	0
235	10	13	KRAMER Fynn	7	f	8	5	5	8	1	2	3	1	0	0	15	1	0	6	0
236	10	14	RUBY Nicolas	7	f	7	3	3	4	1	1	10	1	4	2	9	1	1	5	1
237	10	16	BIBEL Akos	7	f	7	2	5	3	0	1	5	1	3	2	8	0	1	5	1
238	10	17	FUNK Max	7	f	3	2	3	6	0	1	0	0	0	0	1	0	0	1	1
239	10	21	ROBIN Gabriel	7	f	2	2	-1	10	3	1	0	0	0	0	1	0	0	0	1
240	10	22	TONIC Nikola	7	f	1	1	1	3	0	0	0	0	0	0	1	0	0	0	1
241	10	24	SITAR HAFNER Dan	7	t	0	0	-5	0	0	0	28	5	7	5	0	0	0	0	0
242	11	1	HONORATO DE ALMEID	4	f	5	2	2	8	1	0	1	1	0	0	7	0	1	4	1
243	11	2	CAVALCANTI DE OLIVEI	4	f	0	0	0	11	0	0	0	0	0	0	1	0	0	0	0
244	11	3	MADEJ Maciej	4	f	11	4	-2	10	4	1	29	2	10	7	27	4	3	10	0
245	11	4	MARECHAL Adrien	4	f	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0
246	11	5	LOYOLA LAVIN Nelson	4	f	10	1	2	8	1	0	5	0	5	4	22	5	2	10	1
247	11	6	GARCIA Pedro	4	f	3	0	-3	7	2	0	0	0	0	0	15	3	1	3	0
248	11	11	MANGEN Tim	4	f	1	1	-2	9	2	0	0	0	0	0	3	0	1	0	1
249	11	12	MEYERS Dan	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
250	11	13	MARECHAL Yann	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
251	11	14	MICHOTTE Arthur	4	f	1	0	1	1	0	0	0	0	0	0	2	0	0	1	0
252	11	16	MADEJ Jakub	4	t	0	0	-3	0	0	0	26	3	13	10	0	0	0	0	0
253	11	18	MARETTE William	4	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
254	11	19	HUKEL Jakub	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
255	11	1	AUZANI Leonardo	2	f	5	3	3	17	2	0	1	0	0	0	7	0	0	3	2
256	11	2	MARINHO NOVAIS Sam	2	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
257	11	3	CALHOUN Cameron	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
258	11	4	MARINHO NOVAIS Sim	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
259	11	5	MAGGIOLO Enzo	2	f	0	0	-1	1	1	0	0	0	0	0	1	0	0	0	0
260	11	6	BRAAS Gilles	2	f	4	1	1	12	3	1	1	0	0	0	5	0	0	3	0
261	11	7	MILOSEVIC Boris	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
262	11	8	MATILDE DA LUZ Ryan	2	f	12	8	10	11	1	1	0	0	0	0	8	1	0	6	5
263	11	10	ARAB Sina	2	f	7	1	2	10	1	1	9	1	7	4	14	1	2	6	0
264	11	13	CZAPOR Leon Eric	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
265	11	14	HALDORSEN Jan	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
266	11	15	GAJIN Mareja	2	f	16	7	10	13	3	1	0	0	0	0	23	2	1	14	1
267	11	17	TOPALOV Todor	2	f	7	3	1	9	1	0	20	2	7	6	15	3	0	7	0
268	11	23	GARBO Lorenzo	2	t	0	0	0	0	0	0	14	0	9	5	0	0	0	0	0
269	12	1	NIZARD Gil	1	f	2	2	0	17	2	1	0	0	0	0	1	0	0	1	0
270	12	2	BIVER Antoine	1	f	7	3	2	12	2	1	0	0	0	0	10	3	0	5	1
271	12	3	WAGNER Victor	1	f	0	0	0	5	0	0	0	0	0	0	0	0	0	0	0
272	12	5	SOMMERHALTER Vince	1	f	4	2	4	2	0	0	0	0	0	0	6	0	0	4	0
273	12	6	BARTH Frederic	1	t	0	0	-2	0	0	0	19	2	10	7	0	0	0	0	0
274	12	10	HOFFMANN Maxime	1	f	9	5	6	9	0	0	0	0	0	0	15	1	2	6	3
275	12	13	FELLINGER Felix	1	f	16	8	13	11	1	0	0	0	0	0	26	2	0	13	3
276	12	15	VOSAHLO Frantisek	1	f	10	5	4	9	3	0	18	1	12	9	20	2	0	10	0
277	12	28	DARROSA JANKOVIC Ni	1	f	5	3	-5	9	2	1	14	2	6	4	16	5	1	3	1
278	12	1	WOLLES Sam	6	f	4	2	2	5	1	0	8	1	2	1	10	0	0	4	0
279	12	6	ENGELDINGER Tom	6	f	5	3	-2	8	2	0	1	0	1	1	16	2	3	3	2
280	12	7	SZTURMA Nicolas	6	f	4	0	-7	9	0	0	15	2	6	4	22	6	3	4	0
281	12	10	THIES Joey	6	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
282	12	11	HONG Joseph	6	f	0	0	0	7	0	0	0	0	0	0	0	0	0	0	0
283	12	18	DZINIC Aziz	6	f	5	3	-2	7	2	0	17	3	4	0	18	1	1	5	0
284	12	19	BOLLENDORFF Frank	6	f	4	2	2	4	0	0	0	0	0	0	15	1	1	4	0
285	12	55	WEIRIG Yann	6	f	9	2	4	12	3	0	2	0	0	0	16	2	0	9	0
286	12	69	BESCH Tim	6	t	0	0	-1	0	0	0	20	1	5	4	0	0	0	0	0
287	12	77	BETTI Raphael	6	f	2	0	0	8	1	0	1	1	0	0	2	0	0	1	1
288	13	1	HONORATO DE ALMEID	4	f	7	3	6	15	0	0	2	1	1	0	7	0	0	5	2
289	13	2	CAVALCANTI DE OLIVEI	4	f	1	1	1	12	0	1	0	0	0	0	0	0	0	0	0
290	13	3	MADEJ Maciej	4	f	11	5	5	10	1	2	17	1	8	4	14	0	4	7	2
291	13	4	MARECHAL Adrien	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
292	13	5	LOYOLA LAVIN Nelson	4	f	14	6	13	12	1	1	13	0	8	6	24	0	0	13	0
293	13	6	GARCIA Pedro	4	f	13	5	7	11	1	3	0	0	0	0	26	2	3	9	1
294	13	11	MANGEN Tim	4	f	4	2	1	12	1	0	1	1	0	0	4	1	0	2	2
295	13	12	MEYERS Dan	4	f	0	0	-1	2	1	0	0	0	0	0	0	0	0	0	0
296	13	13	MARECHAL Yann	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
297	13	14	MICHOTTE Arthur	4	f	2	2	2	0	0	0	0	0	0	0	1	0	0	1	1
298	13	16	MADEJ Jakub	4	t	0	0	-2	0	0	0	12	2	6	2	0	0	0	0	0
299	13	18	MARETTE William	4	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
300	13	19	HUKEL Jakub	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
301	13	1	SPEIDEL Karim	3	f	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0
302	13	4	METZGER Loris	3	f	4	1	-1	6	0	0	16	2	8	3	15	2	1	3	1
303	13	8	BOLLENDORFF Pol	3	f	1	0	-3	1	0	0	10	2	3	2	6	1	1	1	0
304	13	9	HIRTZ WEIS Sam	3	f	4	2	2	9	0	0	1	0	1	1	5	1	1	2	2
305	13	11	RZYMIANSKI Radoslaw	3	f	14	7	4	10	1	2	21	4	6	5	24	2	3	11	1
306	13	12	SINDECUSE Noah	3	f	2	0	0	10	2	0	0	0	0	0	3	0	0	2	0
307	13	14	WILDGEN Charel	3	f	0	0	0	0	0	0	0	0	0	0	1	0	0	0	0
308	13	17	DA SILVA MARQUES Ma	3	t	0	0	-3	0	0	0	5	3	1	1	0	0	0	0	0
309	13	18	OESCH Noah	3	f	13	3	4	7	3	0	0	0	0	0	27	4	2	12	1
310	13	23	STEIN Max	3	t	0	0	-1	0	0	0	16	1	4	1	0	0	0	0	0
311	13	44	MAZUR Marcel	3	f	3	1	-1	10	3	0	0	0	0	0	5	1	0	1	2
312	14	1	NIZARD Gil	1	f	0	0	-4	8	3	0	0	0	0	0	3	1	0	0	0
313	14	4	BIVER Antoine	1	f	4	1	-1	8	2	0	0	0	0	0	8	3	0	2	3
314	14	5	SOMMERHALTER Vince	1	f	3	1	-3	8	3	0	3	0	0	0	13	1	2	3	0
315	14	7	FELLINGER Felix	1	f	0	0	-8	3	1	0	0	0	0	0	15	3	4	0	0
316	14	10	HOFFMANN Maxime	1	f	7	1	6	7	1	0	0	0	0	0	8	0	0	6	2
317	14	15	VOSAHLO Frantisek	1	f	11	2	1	11	4	1	24	3	11	5	16	2	1	9	1
318	14	16	LUMIA Yoan	1	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
319	14	28	DARROSA JANKOVIC Ni	1	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
320	14	51	SANTOSI Peter	1	f	0	0	-8	4	0	0	12	4	3	0	8	3	1	0	0
321	14	54	PEREIRA Loic	1	f	1	0	1	2	0	0	0	0	0	0	4	0	0	1	0
322	14	58	BARTH Frederic	1	t	0	0	-2	0	0	0	25	2	12	9	0	0	0	0	0
323	14	1	HONORATO DE ALMEID	4	f	9	7	9	12	0	0	0	0	0	0	8	0	0	6	3
324	14	2	CAVALCANTI DE OLIVEI	4	f	1	0	-1	16	1	0	0	0	0	0	3	0	1	0	1
325	14	3	MADEJ Maciej	4	f	12	7	5	14	3	1	6	0	1	1	16	4	0	9	2
326	14	4	MARECHAL Adrien	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
327	14	5	LOYOLA LAVIN Nelson	4	f	5	1	3	3	1	0	3	0	2	1	10	0	1	5	0
328	14	6	GARCIA Pedro	4	f	11	2	3	9	1	1	0	0	0	0	24	7	0	9	1
329	14	11	MANGEN Tim	4	f	5	3	4	11	0	0	0	0	0	0	5	0	1	4	1
330	14	18	MARETTE William	4	t	0	0	-1	0	0	0	26	1	13	7	0	0	0	0	0
331	14	19	HUKEL Jakub	4	f	3	1	-4	8	3	1	2	0	1	1	6	1	3	2	0
332	15	2	ARAPI Adri	8	f	0	0	0	4	0	0	0	0	0	0	2	0	0	0	0
333	15	3	QERRAXHIJA Klaudio	8	t	0	0	0	0	0	0	8	0	6	2	0	0	0	0	0
334	15	4	DATUS Moise	8	f	19	10	16	9	3	1	2	0	0	0	22	0	0	16	2
335	15	5	JUTTEL Mick	8	f	3	1	1	6	1	1	0	0	0	0	8	0	1	2	0
336	15	8	PAVELKA Tomas	8	f	5	3	4	7	0	2	3	0	2	0	6	1	0	3	0
337	15	9	ALAGIC Adonis	8	f	4	4	4	23	0	4	0	0	0	0	0	0	0	0	0
338	15	14	ZUIDBERG Chris	8	f	7	4	5	2	1	0	7	0	5	2	12	0	1	6	1
339	15	17	SONNET Francois	8	f	3	2	1	1	0	0	0	0	0	0	4	1	1	2	1
340	15	18	ZEHREN David	8	f	8	6	7	9	0	0	0	0	0	0	9	1	0	4	4
341	15	19	FISCHER Hugo	8	f	14	9	12	10	1	5	0	0	0	0	9	1	0	6	3
342	15	21	KUHBERG Armin	8	f	1	1	1	3	0	0	0	0	0	0	1	0	0	1	0
343	15	22	JANSEN Miguel	8	t	0	0	-2	0	0	0	9	2	2	1	0	0	0	0	0
344	15	3	HINKEL Sam	6	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
345	15	5	EVEN Philippe	6	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
346	15	6	ENGELDINGER Tom	6	f	5	1	4	6	1	1	0	0	0	0	8	0	0	4	0
347	15	10	THIES Joey	6	t	0	0	-12	0	0	0	20	12	3	2	0	0	0	0	0
348	15	11	HONG Joseph	6	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
349	15	18	DZINIC Aziz	6	f	4	1	-3	6	0	0	14	4	4	2	14	0	3	3	1
350	15	19	BOLLENDORFF Frank	6	f	2	0	-3	4	0	0	1	1	0	0	15	1	3	2	0
351	15	55	WEIRIG Yann	6	f	5	1	1	5	0	0	0	0	0	0	19	1	3	4	1
352	15	69	BESCH Tim	6	f	3	0	-8	5	2	0	32	4	6	4	12	3	2	3	0
353	15	77	BETTI Raphael	6	f	1	1	0	6	0	1	1	0	0	0	7	1	0	0	1
354	16	1	AUZANI Leonardo	2	f	6	2	5	10	1	1	1	0	0	0	6	0	0	4	1
355	16	2	MARINHO NOVAIS Sam	2	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
356	16	3	CALHOUN Cameron	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
357	16	4	MARINHO NOVAIS Sim	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
358	16	5	MAGGIOLO Enzo	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
359	16	6	BRAAS Gilles	2	f	2	2	0	14	2	1	0	0	0	0	1	0	0	1	1
360	16	7	MILOSEVIC Boris	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
361	16	8	MATILDE DA LUZ Ryan	2	f	8	5	7	9	1	1	0	0	0	0	6	0	0	4	3
362	16	9	INEMEK Louis	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
363	16	10	ARAB Sina	2	f	13	9	7	12	1	3	9	1	3	3	19	1	3	9	1
364	16	14	HALDORSEN Jan	2	f	1	1	1	3	0	1	0	0	0	0	0	0	0	0	0
365	16	15	GAJIN Mareja	2	f	15	7	12	7	2	0	0	0	0	0	21	1	0	14	1
366	16	17	TOPALOV Todor	2	f	7	2	4	19	0	1	9	2	3	1	8	1	0	6	1
367	16	23	GARBO Lorenzo	2	t	0	0	-2	0	0	0	18	2	5	3	0	0	0	0	0
368	16	1	HONORATO DE ALMEID	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
369	16	2	CAVALCANTI DE OLIVEI	4	f	0	0	-1	8	1	0	0	0	0	0	0	0	0	0	0
370	16	3	MADEJ Maciej	4	f	8	2	-4	7	2	0	30	7	7	3	15	2	1	7	1
371	16	4	MARECHAL Adrien	4	f	7	0	6	6	1	0	0	0	0	0	9	0	0	6	1
372	16	5	LOYOLA LAVIN Nelson	4	f	5	0	-1	4	1	0	5	0	2	2	17	4	1	5	0
373	16	6	GARCIA Pedro	4	f	12	3	4	7	3	0	0	0	0	0	19	2	3	11	1
374	16	7	CLEES Jules	4	f	0	0	0	0	0	0	0	0	0	0	1	0	0	0	0
375	16	8	HEIRENS Sony	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
376	16	11	MANGEN Tim	4	f	1	0	-5	12	2	0	2	2	0	0	4	0	2	1	0
377	16	13	MARECHAL Yann	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
378	16	14	MICHOTTE Arthur	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
379	16	16	MADEJ Jakub	4	t	0	0	-1	0	0	0	5	1	1	1	0	0	0	0	0
380	16	18	MARETTE William	4	t	0	0	-2	0	0	0	19	2	9	5	0	0	0	0	0
381	16	19	HUKEL Jakub	4	f	3	0	-1	4	1	0	6	2	2	1	10	0	1	3	0
382	17	3	WAGNER Victor	1	f	1	0	-1	8	2	0	0	0	0	0	1	0	0	1	0
383	17	4	BIVER Antoine	1	f	0	0	-6	8	3	0	0	0	0	0	10	1	2	0	0
384	17	5	SOMMERHALTER Vince	1	f	0	0	-2	4	0	0	8	0	4	2	4	1	1	0	0
385	17	7	FELLINGER Felix	1	f	5	1	-1	3	0	0	0	0	0	0	28	5	1	5	0
386	17	10	HOFFMANN Maxime	1	f	9	4	4	5	2	0	1	1	0	0	14	0	2	7	2
387	17	15	VOSAHLO Frantisek	1	f	5	2	0	7	0	0	11	1	4	3	19	2	2	4	1
388	17	28	DARROSA JANKOVIC Ni	1	f	5	1	-3	11	1	1	24	1	3	1	16	4	2	4	0
389	17	58	BARTH Frederic	1	t	0	0	-7	0	0	0	21	7	7	4	0	0	0	0	0
390	17	1	SPEIDEL Karim	3	f	2	2	1	4	1	2	0	0	0	0	0	0	0	0	0
391	17	4	METZGER Loris	3	f	4	2	2	3	0	0	3	1	0	0	7	1	0	4	0
392	17	6	ZENDER Christophe	3	f	2	1	-2	3	1	0	0	0	0	0	8	1	2	2	0
393	17	7	NEME RODRIGUES Nad	3	f	6	4	5	15	1	1	0	0	0	0	11	0	0	5	0
394	17	8	BOLLENDORFF Pol	3	f	13	8	11	12	1	1	5	0	1	0	14	1	0	8	4
395	17	9	HIRTZ WEIS Sam	3	f	4	3	4	4	0	0	0	0	0	0	2	0	0	1	3
396	17	11	RZYMIANSKI Radoslaw	3	f	10	3	2	13	2	0	21	2	10	7	26	4	0	10	0
397	17	12	SINDECUSE Noah	3	f	3	2	3	0	0	0	0	0	0	0	0	0	0	0	3
398	17	17	DA SILVA MARQUES Ma	3	t	0	0	0	0	0	0	2	0	0	0	0	0	0	0	0
399	17	18	OESCH Noah	3	f	5	2	1	6	1	0	0	0	0	0	13	2	1	5	0
400	17	23	STEIN Max	3	t	0	0	0	0	0	0	6	0	1	1	0	0	0	0	0
401	17	44	MAZUR Marcel	3	f	2	2	1	13	1	0	0	0	0	0	3	0	0	2	0
402	18	1	SPEIDEL Karim	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
403	18	4	METZGER Loris	3	f	3	2	-10	6	1	0	29	5	11	10	21	6	1	3	0
404	18	6	ZENDER Christophe	3	f	0	0	-2	4	0	0	0	0	0	0	6	2	0	0	0
405	18	7	NEME RODRIGUES Nad	3	f	9	2	8	7	0	0	0	0	0	0	20	0	1	8	1
406	18	9	HIRTZ WEIS Sam	3	f	6	1	5	6	0	0	0	0	0	0	7	1	0	5	1
407	18	11	RZYMIANSKI Radoslaw	3	f	4	1	-10	7	2	0	18	3	7	5	22	3	6	4	0
408	18	14	WILDGEN Charel	3	f	1	1	-1	4	2	0	0	0	0	0	1	0	0	0	1
409	18	23	STEIN Max	3	t	0	0	-6	0	0	0	20	6	8	5	0	0	0	0	0
410	18	44	MAZUR Marcel	3	f	4	1	-1	8	3	1	0	0	0	0	7	0	2	2	2
411	18	2	ARAPI Adri	8	f	4	3	2	8	0	1	0	0	0	0	3	2	0	1	2
412	18	3	QERRAXHIJA Klaudio	8	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
413	18	4	DATUS Moise	8	f	13	5	6	5	3	0	7	0	2	1	24	1	3	13	0
414	18	5	JUTTEL Mick	8	f	1	0	1	0	0	0	0	0	0	0	2	0	0	1	0
415	18	8	PAVELKA Tomas	8	f	2	2	1	2	0	0	7	0	2	1	9	0	1	2	0
416	18	9	ALAGIC Adonis	8	f	2	1	1	16	1	1	1	0	0	0	1	0	0	1	0
417	18	14	ZUIDBERG Chris	8	f	5	3	4	9	0	0	5	1	1	1	6	0	0	5	0
418	18	16	GLESENER Philippe	8	t	0	0	-1	0	0	0	13	1	6	3	0	0	0	0	0
419	18	17	SONNET Francois	8	f	0	0	0	5	0	0	0	0	0	0	3	0	0	0	0
420	18	18	ZEHREN David	8	f	3	2	3	12	0	0	0	0	0	0	2	0	0	1	2
421	18	19	FISCHER Hugo	8	f	24	18	18	16	3	4	0	0	0	0	24	2	1	14	6
422	18	22	JANSEN Miguel	8	f	0	0	0	1	0	0	1	0	0	0	0	0	0	0	0
423	19	3	WAGNER Victor	1	f	1	1	1	6	0	0	0	0	0	0	1	0	0	0	1
424	19	7	FELLINGER Felix	1	f	7	3	-6	6	2	0	0	0	0	0	34	8	3	6	1
425	19	10	HOFFMANN Maxime	1	f	4	2	2	6	0	0	0	0	0	0	9	2	0	2	2
426	19	15	BIVER Antoine	1	f	3	1	1	14	2	1	0	0	0	0	6	0	0	2	0
427	19	17	BLANCO Juan Carlos	1	f	0	0	0	2	0	0	0	0	0	0	1	0	0	0	0
428	19	28	DARROSA JANKOVIC Ni	1	f	7	2	-4	9	3	0	21	5	5	1	15	2	1	6	1
429	19	51	SANTOSI Peter	1	f	7	2	-2	10	0	1	12	5	1	1	14	2	2	6	0
430	19	54	PEREIRA Loic	1	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
431	19	58	BARTH Frederic	1	t	0	0	-4	0	0	0	29	4	12	6	0	0	0	0	0
432	19	71	SOMMERHALTER Vince	1	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
433	19	1	SCHUBERT Jared	7	t	0	0	0	0	0	0	4	0	4	2	0	0	0	0	0
434	19	2	KOLACNY Jaromir	7	f	14	7	9	10	2	2	0	0	0	0	23	2	1	12	0
435	19	5	LANDUYDT Olivier	7	f	4	2	2	12	1	0	0	0	0	0	6	1	0	3	1
436	19	6	BARNES Issac	7	f	2	0	-2	2	1	0	2	0	1	0	10	1	2	2	0
437	19	8	VARGAS Lyndon	7	f	1	1	-1	7	1	1	0	0	0	0	2	1	0	0	0
438	19	9	WEBER Steve	7	f	8	4	5	6	1	0	6	2	2	1	12	0	0	7	1
439	19	11	HILBERT Colin	7	f	8	4	5	5	1	1	12	0	6	2	9	1	1	6	1
440	19	13	KRAMER Fynn	7	f	5	2	0	7	2	1	10	2	1	0	7	0	1	4	0
441	19	14	RUBY Nicolas	7	f	0	0	-2	2	1	0	0	0	0	0	4	1	0	0	0
442	19	17	FUNK Max	7	f	6	6	5	17	1	2	0	0	0	0	1	0	0	1	3
443	19	21	ROBIN Gabriel	7	f	4	2	1	7	2	0	0	0	0	0	9	1	0	4	0
444	19	24	SITAR HAFNER Dan	7	t	0	0	-1	0	0	0	12	1	6	4	0	0	0	0	0
445	20	1	SCHUBERT Jared	7	t	0	0	-5	0	0	0	22	5	14	11	0	0	0	0	0
446	20	2	KOLACNY Jaromir	7	f	21	6	14	15	2	2	0	0	0	0	38	2	3	16	3
447	20	4	KIFFER Max	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
448	20	5	LANDUYDT Olivier	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
449	20	6	BARNES Issac	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
450	20	8	VARGAS Lyndon	7	f	14	10	14	18	0	2	0	0	0	0	15	0	0	6	6
451	20	9	WEBER Steve	7	f	20	8	7	21	1	3	34	6	9	5	35	3	3	16	1
452	20	11	HILBERT Colin	7	f	15	5	-1	13	5	0	29	5	11	9	32	4	2	14	1
453	20	13	KRAMER Fynn	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
454	20	14	RUBY Nicolas	7	f	0	0	-1	1	1	0	0	0	0	0	0	0	0	0	0
455	20	17	FUNK Max	7	f	1	0	0	16	1	0	0	0	0	0	2	0	0	1	0
456	20	21	ROBIN Gabriel	7	f	8	2	5	19	2	0	1	0	1	1	9	1	0	6	2
457	20	22	TONIC Nikola	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
458	20	24	SITAR HAFNER Dan	7	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
459	20	2	ARAPI Adri	8	f	4	1	2	9	2	1	0	0	0	0	5	0	0	2	1
460	20	3	QERRAXHIJA Klaudio	8	t	0	0	-2	0	0	0	15	2	9	7	0	0	0	0	0
461	20	4	DATUS Moise	8	f	19	10	7	20	3	6	16	2	7	5	29	2	5	13	0
462	20	5	JUTTEL Mick	8	f	2	0	-2	3	1	0	4	1	0	0	7	0	2	2	0
463	20	8	PAVELKA Tomas	8	f	4	2	-2	5	1	0	8	2	2	0	12	2	1	4	0
464	20	9	ALAGIC Adonis	8	f	4	3	4	15	0	2	2	0	0	0	0	0	0	0	2
465	20	14	ZUIDBERG Chris	8	f	23	9	12	17	3	1	19	3	9	4	42	2	3	20	2
466	20	16	GLESENER Philippe	8	t	0	0	-2	0	0	0	22	2	11	6	0	0	0	0	0
467	20	17	SONNET Francois	8	f	2	1	0	11	2	1	0	0	0	0	5	0	0	1	0
468	20	18	ZEHREN David	8	f	7	2	6	15	0	0	2	1	1	0	7	0	0	5	2
469	20	19	FISCHER Hugo	8	f	13	1	6	7	4	0	3	0	1	0	27	1	2	12	1
470	21	1	SPEIDEL Karim	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
471	21	4	METZGER Loris	3	f	12	3	2	8	1	0	23	0	13	7	39	5	4	12	0
472	21	6	ZENDER Christophe	3	f	5	3	0	10	1	2	0	0	0	0	16	3	1	3	0
473	21	7	NEME RODRIGUES Nad	3	f	10	3	6	10	2	0	1	0	0	0	20	0	2	8	2
474	21	8	BOLLENDORFF Pol	3	f	11	3	2	13	1	1	23	0	8	6	31	4	4	8	2
475	21	9	HIRTZ WEIS Sam	3	f	1	1	-2	7	0	1	0	0	0	0	7	1	2	0	0
476	21	12	SINDECUSE Noah	3	f	0	0	-3	7	2	0	0	0	0	0	2	0	1	0	0
477	21	17	DA SILVA MARQUES Ma	3	t	0	0	-3	0	0	0	20	3	7	4	0	0	0	0	0
478	21	18	OESCH Noah	3	f	5	0	2	3	0	0	0	0	0	0	14	0	3	5	0
479	21	23	STEIN Max	3	t	0	0	-3	0	0	0	10	3	5	1	0	0	0	0	0
480	21	44	MAZUR Marcel	3	f	6	2	0	14	5	1	0	0	0	0	6	1	0	3	2
481	21	1	SCHUBERT Jared	7	t	0	0	0	0	0	0	9	0	4	1	0	0	0	0	0
482	21	2	KOLACNY Jaromir	7	f	16	6	12	16	2	0	0	0	0	0	30	1	1	14	2
483	21	5	LANDUYDT Olivier	7	f	7	1	4	15	1	0	1	0	1	1	9	1	1	4	3
484	21	8	VARGAS Lyndon	7	f	10	5	9	14	0	0	1	0	0	0	10	0	1	5	5
485	21	9	WEBER Steve	7	f	12	5	5	13	4	0	23	2	16	11	15	1	0	8	4
486	21	11	HILBERT Colin	7	f	11	5	3	12	4	0	15	3	6	4	16	0	1	11	0
487	21	13	KRAMER Fynn	7	f	2	0	-4	2	1	0	11	3	2	0	10	1	1	2	0
488	21	14	RUBY Nicolas	7	f	0	0	-3	1	1	0	0	0	0	0	6	1	1	0	0
489	21	17	FUNK Max	7	f	7	5	5	19	2	3	0	0	0	0	2	0	0	2	3
490	21	24	SITAR HAFNER Dan	7	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
491	22	2	ARAPI Adri	8	f	0	0	-1	2	1	0	0	0	0	0	0	0	0	0	0
492	22	3	QERRAXHIJA Klaudio	8	t	0	0	0	0	0	0	15	0	6	5	0	0	0	0	0
493	22	4	DATUS Moise	8	f	20	5	13	9	2	2	7	0	2	1	31	3	2	18	0
494	22	5	JUTTEL Mick	8	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
495	22	8	PAVELKA Tomas	8	f	8	1	0	10	2	0	19	2	12	6	13	2	2	8	0
496	22	9	ALAGIC Adonis	8	f	1	1	0	11	1	0	0	0	0	0	1	0	0	0	1
497	22	14	ZUIDBERG Chris	8	f	6	2	-1	6	2	1	15	2	6	4	9	0	3	4	1
498	22	17	SONNET Francois	8	f	1	1	0	2	0	1	0	0	0	0	2	0	1	0	0
499	22	18	ZEHREN David	8	f	0	0	-2	7	1	0	0	0	0	0	3	1	0	0	0
500	22	19	FISCHER Hugo	8	f	5	2	-3	10	2	2	9	2	2	2	15	2	2	3	0
501	22	21	KUHBERG Armin	8	f	0	0	-4	5	3	0	0	0	0	0	3	1	0	0	0
502	22	22	JANSEN Miguel	8	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
503	22	1	HONORATO DE ALMEID	4	f	13	7	12	15	0	0	0	0	0	0	10	1	0	9	4
504	22	2	CAVALCANTI DE OLIVEI	4	f	1	0	1	12	0	0	0	0	0	0	2	0	0	1	0
505	22	3	MADEJ Maciej	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
506	22	4	MARECHAL Adrien	4	f	3	1	0	16	1	0	0	0	0	0	5	2	0	3	0
507	22	5	LOYOLA LAVIN Nelson	4	f	9	3	6	7	1	0	18	0	11	9	12	1	1	8	1
508	22	6	GARCIA Pedro	4	f	13	8	8	10	2	2	0	0	0	0	13	3	0	7	4
509	22	8	HEIRENS Sony	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
510	22	11	MANGEN Tim	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
511	22	13	MARECHAL Yann	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
512	22	14	MICHOTTE Arthur	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
513	22	16	MADEJ Jakub	4	t	0	0	-3	0	0	0	17	3	9	5	0	0	0	0	0
514	22	18	MARETTE William	4	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
515	22	19	HUKEL Jakub	4	f	12	4	1	13	4	1	13	5	4	1	20	1	1	10	1
516	23	1	DEINEGA Vladimir	5	f	6	3	2	7	2	0	4	0	1	1	17	1	1	6	0
517	23	3	DOBRE Sebastian	5	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
518	23	4	MIRINKOVIC Luka	5	f	14	5	11	11	3	0	0	0	0	0	15	0	0	11	3
519	23	8	BILAN Filip	5	f	13	9	6	19	5	4	0	0	0	0	13	2	0	8	1
520	23	9	VUJOVIC Pavle	5	f	4	2	1	11	3	0	0	0	0	0	3	0	0	1	3
521	23	10	POLFER Felix	5	f	2	2	2	3	0	1	2	0	1	1	2	0	0	1	0
522	23	12	CONSTANTINOU Michai	5	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
523	23	22	BRISBOIS Nicolas	5	t	0	0	-5	0	0	0	30	5	17	12	0	0	0	0	0
524	23	24	HAJ ISMAIL Mohamed	5	f	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0
525	23	77	DUDA Karol	5	f	10	2	9	12	0	0	0	0	0	0	9	0	1	7	3
526	23	82	LOMACZ Jakub	5	f	7	2	-1	10	2	0	12	1	4	4	16	4	1	7	0
527	23	1	WOLLES Sam	6	f	1	0	-1	3	0	0	9	0	4	1	7	1	1	1	0
528	23	3	HINKEL Sam	6	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
529	23	5	EVEN Philippe	6	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
530	23	6	ENGELDINGER Tom	6	f	9	2	2	7	2	0	1	1	0	0	18	3	1	9	0
531	23	7	SZTURMA Nicolas	6	f	8	5	0	7	0	0	14	2	6	3	19	2	4	7	1
532	23	10	THIES Joey	6	t	0	0	-8	0	0	0	27	8	3	2	0	0	0	0	0
533	23	18	DZINIC Aziz	6	f	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0
534	23	19	BOLLENDORFF Frank	6	f	2	1	-4	9	3	0	0	0	0	0	8	2	1	2	0
535	23	55	WEIRIG Yann	6	f	6	1	4	9	1	0	0	0	0	0	9	1	0	5	1
536	23	69	BESCH Tim	6	f	2	0	-3	8	0	0	8	1	1	1	13	2	2	2	0
537	23	77	BETTI Raphael	6	f	4	4	1	12	2	0	0	0	0	0	9	0	1	3	1
538	24	1	SCHUBERT Jared	7	t	0	0	0	0	0	0	15	0	8	6	0	0	0	0	0
539	24	2	KOLACNY Jaromir	7	f	9	4	6	10	0	1	0	0	0	0	18	2	1	6	2
540	24	4	KIFFER Max	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
541	24	5	LANDUYDT Olivier	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
542	24	8	VARGAS Lyndon	7	f	9	5	7	17	1	0	0	0	0	0	12	0	1	7	2
543	24	9	WEBER Steve	7	f	13	9	5	8	3	1	14	3	10	8	19	0	2	8	4
544	24	11	HILBERT Colin	7	f	9	6	5	8	3	1	8	0	3	2	11	0	1	7	1
545	24	13	KRAMER Fynn	7	f	5	1	-1	9	3	1	8	2	3	1	9	1	0	4	0
546	24	14	RUBY Nicolas	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
547	24	17	FUNK Max	7	f	5	4	5	10	0	1	0	0	0	0	2	0	0	2	2
548	24	21	ROBIN Gabriel	7	f	7	4	6	14	1	0	0	0	0	0	5	0	0	4	3
549	24	22	TONIC Nikola	7	f	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0
550	24	24	SITAR HAFNER Dan	7	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
551	24	1	DEINEGA Vladimir	5	f	1	0	-9	5	2	0	19	4	7	5	11	2	2	1	0
552	24	3	DOBRE Sebastian	5	f	0	0	-1	1	1	0	0	0	0	0	1	0	0	0	0
553	24	4	MARINKOVIC Luka	5	f	7	3	4	10	2	2	0	0	0	0	12	0	1	5	0
554	24	8	BILAN Filip	5	f	9	1	1	10	1	0	0	0	0	0	24	0	7	8	1
555	24	9	VUJOVIC Pavle	5	f	4	1	2	4	2	0	0	0	0	0	4	0	0	3	1
556	24	10	POLFER Felix	5	f	5	2	2	9	1	1	12	1	4	1	8	0	1	4	0
557	24	12	CONSTANTINOU Michai	5	f	3	0	-3	4	1	0	11	1	2	2	11	2	2	3	0
558	24	22	BRISBOIS Nicolas	5	t	0	0	-3	0	0	0	20	3	9	6	0	0	0	0	0
559	24	24	HAJ ISMAIL Mohamed	5	f	3	2	-1	3	0	0	4	2	1	1	5	2	0	2	1
560	24	77	DUDA Karol	5	f	6	4	4	9	0	1	0	0	0	0	6	1	1	3	2
561	24	82	LOMACZ Jakub	5	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
562	25	2	ARAPI Adri	8	f	0	0	0	5	0	0	0	0	0	0	0	0	0	0	0
563	25	3	QERRAXHIJA Klaudio	8	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
564	25	4	DATUS Moise	8	f	20	8	6	24	6	6	22	4	3	1	28	4	0	14	0
565	25	5	JUTTEL Mick	8	f	0	0	-1	1	1	0	1	0	0	0	2	0	0	0	0
566	25	8	PAVELKA Tomas	8	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
567	25	9	ALAGIC Adonis	8	f	0	0	0	9	0	0	0	0	0	0	0	0	0	0	0
568	25	14	ZUIDBERG Chris	8	f	18	7	12	14	1	2	13	0	10	4	25	2	3	12	4
569	25	17	SONNET Francois	8	f	2	1	1	9	0	0	0	0	0	0	6	0	1	2	0
570	25	18	ZEHREN David	8	f	6	2	6	19	0	0	0	0	0	0	6	0	0	5	1
571	25	19	FISCHER Hugo	8	f	15	11	1	12	4	1	1	0	1	1	27	7	3	12	2
572	25	22	JANSEN Miguel	8	t	0	0	0	0	0	0	16	0	8	2	0	0	0	0	0
573	25	1	SPEIDEL Karim	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
574	25	4	METZGER Loris	3	f	2	0	-9	4	1	0	16	5	3	2	13	3	2	2	0
575	25	7	NEME RODRIGUES Nad	3	f	8	0	1	11	3	0	16	3	1	1	20	1	0	7	1
576	25	8	BOLLENDORFF Pol	3	f	11	2	4	14	1	1	14	5	3	0	18	0	1	10	0
577	25	9	HIRTZ WEIS Sam	3	f	8	1	4	10	2	0	1	0	0	0	8	1	1	4	4
578	25	12	SINDECUSE Noah	3	f	0	0	0	5	0	0	0	0	0	0	2	0	0	0	0
579	25	14	WILDGEN Charel	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
580	25	18	OESCH Noah	3	f	8	1	-5	11	4	0	3	1	0	0	27	5	3	6	2
581	25	23	STEIN Max	3	t	0	0	-5	0	0	0	30	5	10	5	0	0	0	0	0
582	25	44	MAZUR Marcel	3	f	3	2	-4	16	7	1	1	0	0	0	4	0	0	2	0
583	26	1	AUZANI Leonardo	2	f	10	3	9	8	1	0	0	0	0	0	9	0	0	8	2
584	26	2	MARINHO NOVAIS Sam	2	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
585	26	3	CALHOUN Cameron	2	f	0	0	0	3	0	0	0	0	0	0	2	0	0	0	0
586	26	4	MARINHO NOVAIS Sim	2	f	1	1	1	1	0	0	0	0	0	0	1	0	0	1	0
587	26	6	BRAAS Gilles	2	f	5	3	4	7	0	0	0	0	0	0	6	1	0	3	2
588	26	7	MILOSEVIC Boris	2	f	0	0	-1	0	0	0	0	0	0	0	2	0	1	0	0
589	26	8	MATILDE DA LUZ Ryan	2	f	6	4	3	16	1	0	0	0	0	0	8	2	0	6	0
590	26	9	INEMEK Louis	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
591	26	10	ARAB Sina	2	f	14	8	7	12	1	1	13	1	8	7	20	3	2	11	2
592	26	13	CZAPOR Leon Eric	2	f	1	1	-1	1	1	0	1	0	0	0	4	1	0	1	0
593	26	14	HALDORSEN Jan	2	f	0	0	0	0	0	0	0	0	0	0	1	0	0	0	0
594	26	15	GAJIN Mareja	2	f	8	5	1	13	2	2	0	0	0	0	11	2	3	5	1
595	26	17	TOPALOV Todor	2	f	13	5	8	12	2	2	7	2	2	2	16	1	0	11	0
596	26	23	GARBO Lorenzo	2	t	0	0	-1	0	0	0	20	1	13	6	0	0	0	0	0
597	26	1	DEINEGA Vladimir	5	f	9	0	0	8	3	0	22	3	7	6	25	1	2	7	2
598	26	3	DOBRE Sebastian	5	f	0	0	0	4	0	0	0	0	0	0	1	0	0	0	0
599	26	4	MIRINKOVIC Luka	5	f	4	2	2	7	1	1	0	0	0	0	4	1	0	2	2
600	26	8	BILAN Filip	5	f	2	1	-3	7	1	0	0	0	0	0	14	2	2	2	0
601	26	9	VUJOVIC Pavle	5	f	2	0	1	6	0	0	0	0	0	0	3	1	0	2	0
602	26	12	CONSTANTINOU Michai	5	f	7	0	-4	8	1	0	20	5	5	4	17	2	3	6	1
603	26	17	POLFER Felix	5	t	0	0	-2	0	0	0	11	2	2	1	0	0	0	0	0
604	26	22	BRISBOIS Nicolas	5	t	0	0	-1	0	0	0	11	1	3	2	0	0	0	0	0
605	26	24	HAJ ISMAIL Mohamed	5	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
606	26	27	COURRIOUX Quentin	5	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
607	26	77	DUDA Karol	5	f	3	2	0	9	2	1	1	0	1	0	8	1	0	1	1
608	26	82	LOMACZ Jakub	5	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
609	27	1	AUZANI Leonardo	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
610	27	2	MARINHO NOVAIS Sam	2	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
611	27	3	CALHOUN Cameron	2	f	3	2	-2	4	1	0	10	1	6	2	9	2	1	3	0
612	27	4	MARINHO NOVAIS Sim	2	f	5	4	5	27	0	3	0	0	0	0	1	0	0	1	1
613	27	5	MAGGIOLO Enzo	2	f	7	4	3	5	1	0	0	0	0	0	18	2	1	7	0
614	27	6	BRAAS Gilles	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
615	27	7	MILOSEVIC Boris	2	f	10	4	8	10	0	0	11	0	7	3	19	0	2	10	0
616	27	8	MATILDE DA LUZ Ryan	2	f	6	2	6	9	0	1	0	0	0	0	7	0	0	5	0
617	27	9	INEMEK Louis	2	f	7	3	2	4	1	1	0	0	0	0	14	3	1	5	1
618	27	10	ARAB Sina	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
619	27	13	CZAPOR Leon Eric	2	f	5	1	3	4	1	1	13	0	6	6	5	1	0	4	0
620	27	14	HALDORSEN Jan	2	f	13	9	12	10	0	0	0	0	0	0	7	0	1	5	8
621	27	17	TOPALOV Todor	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
622	27	23	GARBO Lorenzo	2	t	0	0	-1	0	0	0	8	1	3	2	0	0	0	0	0
623	27	1	NIZARD Gil	1	f	1	1	0	4	1	0	1	0	0	0	1	0	0	1	0
624	27	3	WAGNER Victor	1	f	0	0	-1	7	1	0	0	0	0	0	0	0	0	0	0
625	27	4	BIVER Antoine	1	f	6	2	3	5	1	0	0	0	0	0	8	0	2	2	4
626	27	5	SOMMERHALTER Vince	1	f	2	0	-1	2	0	0	4	1	0	0	7	1	1	2	0
627	27	7	FELLINGER Felix	1	f	4	1	-2	3	1	0	0	0	0	0	17	2	3	4	0
628	27	10	HOFFMANN Maxime	1	f	4	1	1	9	0	0	2	0	1	1	12	3	0	3	1
629	27	12	DIVO Mathis	1	f	2	0	-1	3	0	0	0	0	0	0	9	1	2	1	1
630	27	15	VOSAHLO Frantisek	1	f	4	0	2	5	0	0	6	1	5	4	17	0	1	4	0
631	27	16	QUINTUIS Denis	1	t	0	0	-2	0	0	0	27	2	6	2	0	0	0	0	0
632	27	51	SANTOSI Peter	1	f	7	1	-1	9	2	0	29	3	12	7	17	2	1	7	0
633	27	54	PEREIRA Loic	1	f	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0
634	28	2	ARAPI Adri	8	f	7	5	5	10	2	0	0	0	0	0	7	0	0	6	1
635	28	4	DATUS Moise	8	f	17	12	15	7	1	1	2	0	0	0	21	0	1	13	3
636	28	5	JUTTEL Mick	8	t	0	0	-4	0	0	0	13	4	5	3	0	0	0	0	0
637	28	8	PAVELKA Tomas	8	f	7	4	5	11	0	0	16	1	10	6	13	1	0	7	0
638	28	9	ALAGIC Adonis	8	f	0	0	-1	3	1	0	0	0	0	0	0	0	0	0	0
639	28	14	ZUIDBERG Chris	8	f	4	2	4	2	0	0	0	0	0	0	3	0	0	3	1
640	28	17	SONNET Francois	8	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
641	28	18	ZEHREN David	8	f	4	2	-1	15	2	0	1	1	0	0	6	2	0	2	2
642	28	19	FISCHER Hugo	8	f	9	4	6	12	3	2	7	0	3	1	17	0	0	6	1
643	28	21	KUHBERG Armin	8	f	8	3	4	14	3	1	0	0	0	0	8	1	0	6	1
644	28	22	JANSEN Miguel	8	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
645	28	1	DEINEGA Vladimir	5	f	13	4	6	13	1	1	10	3	3	1	23	0	3	11	1
646	28	3	DOBRE Sebastian	5	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
647	28	4	MIRINKOVIC Luka	5	f	4	1	1	6	3	0	1	0	0	0	11	0	0	4	0
648	28	8	BILAN Filip	5	f	3	0	2	4	0	0	0	0	0	0	9	0	1	3	0
649	28	9	VUJOVIC Pavle	5	f	1	1	-3	9	4	1	0	0	0	0	2	0	0	0	0
650	28	10	POLFER Felix	5	f	4	0	1	3	0	0	4	0	2	1	7	2	1	4	0
651	28	12	CONSTANTINOU Micha	5	f	4	3	-13	6	2	0	34	8	4	1	22	4	3	4	0
652	28	17	LOMACZ Jakub	5	t	0	0	-2	0	0	0	12	2	4	3	0	0	0	0	0
653	28	24	HAJ ISMAIL Mohamed	5	f	1	1	0	4	1	1	0	0	0	0	0	0	0	0	0
654	28	27	COURRIOUX Quentin	5	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
655	28	77	DUDA Karol	5	f	1	0	-1	6	1	0	0	0	0	0	4	0	1	1	0
656	29	1	NIZARD Gil	1	f	3	2	0	18	1	1	0	0	0	0	6	2	0	1	1
657	29	3	WAGNER Victor	1	f	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0
658	29	4	BIVER Antoine	1	f	4	2	0	15	2	1	1	0	1	1	10	1	1	1	2
659	29	5	SOMMERHALTER Vince	1	f	11	5	2	14	0	1	22	1	6	4	30	5	3	9	1
660	29	7	FELLINGER Felix	1	f	17	4	10	10	1	0	0	0	0	0	45	6	0	15	2
661	29	10	HOFFMANN Maxime	1	f	7	2	5	15	1	0	0	0	0	0	10	1	0	5	2
662	29	15	VOSAHLO Frantisek	1	f	15	10	6	15	2	0	22	3	8	3	41	2	2	14	1
663	29	16	LUMIA Yoan	1	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
664	29	51	SANTOSI Peter	1	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
665	29	58	BARTH Frederic	1	t	0	0	-3	0	0	0	38	3	18	14	0	0	0	0	0
666	29	1	DEINEGA Vladimir	5	f	18	3	7	17	4	0	0	0	0	0	45	5	2	17	2
667	29	3	DOBRE Sebastian	5	f	1	0	-1	20	1	0	1	1	0	0	1	0	0	1	0
668	29	8	BILAN Filip	5	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
669	29	11	THEIS Robert	5	f	5	4	2	17	1	2	0	0	0	0	7	2	0	1	2
670	29	12	CONSTANTINOU Michai	5	f	14	6	6	10	2	0	32	0	11	8	40	3	3	14	0
671	29	17	POLFER Felix	5	t	0	0	-2	0	0	0	18	2	9	3	0	0	0	0	0
672	29	24	HAJ ISMAIL Mohamed	5	f	0	0	-1	3	1	0	0	0	0	0	0	0	0	0	0
673	29	27	COURRIOUX Quentin	5	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
674	29	77	DUDA Karol	5	f	4	1	1	11	1	0	0	0	0	0	7	1	1	2	2
675	29	82	LOMACZ Jakub	5	f	18	6	9	18	3	1	30	2	6	4	47	1	3	17	0
676	30	1	DEINEGA Vladimir	5	f	14	9	4	13	2	0	20	1	9	4	34	5	2	12	2
677	30	3	DOBRE Sebastian	5	f	0	0	0	4	0	0	0	0	0	0	0	0	0	0	0
678	30	4	MARINKOVIC Luka	5	f	16	9	10	17	3	2	0	0	0	0	20	2	1	11	3
679	30	8	BILAN Filip	5	f	9	4	1	12	4	2	0	0	0	0	22	4	0	7	0
680	30	9	VUJOVIC Pavle	5	f	2	1	0	10	1	0	0	0	0	0	2	1	0	1	2
681	30	10	POLFER Felix	5	f	5	1	1	9	1	0	20	2	2	2	16	1	0	4	1
682	30	12	CONSTANTINOU Michai	5	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
683	30	22	BRISBOIS Nicolas	5	t	0	0	-1	0	0	0	13	1	9	4	0	0	0	0	0
684	30	24	HAJ ISMAIL Mohamed	5	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
685	30	27	COURRIOUX Quentin	5	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
686	30	77	DUDA Karol	5	f	3	2	2	20	0	0	0	0	0	0	4	1	0	0	3
687	30	82	LOMACZ Jakub	5	f	8	3	0	11	4	1	11	3	6	5	13	1	0	7	0
688	30	1	NIZARD Gil	1	f	3	3	0	13	2	3	0	0	0	0	3	1	0	0	0
689	30	2	BIVER Antoine	1	f	3	2	0	9	1	0	0	0	0	0	12	2	0	2	1
690	30	3	WAGNER Victor	1	f	0	0	0	4	0	0	0	0	0	0	0	0	0	0	0
691	30	6	BARTH Frederic	1	t	0	0	-7	0	0	0	41	7	17	12	0	0	0	0	0
692	30	9	SANTOSI Peter	1	f	6	2	-2	11	0	0	21	2	6	5	18	5	1	6	0
693	30	10	HOFFMANN Maxime	1	f	8	6	0	11	2	2	0	0	0	0	16	3	3	5	1
694	30	13	FELLINGER Felix	1	f	10	4	1	15	2	0	0	0	0	0	34	6	1	9	1
695	30	15	VOSAHLO Frantisek	1	f	5	2	-1	7	0	0	10	1	5	1	18	3	2	5	0
696	30	28	DARROSA JANKOVIC Ni	1	f	3	1	-12	5	4	0	9	1	4	2	17	6	4	3	0
697	31	1	DEINEGA Vladimir	5	f	17	8	4	15	3	4	34	3	9	6	31	1	6	12	1
698	31	3	DOBRE Sebastian	5	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
699	31	8	BILAN Filip	5	f	10	3	0	20	3	0	0	0	0	0	29	5	2	9	1
700	31	9	VUJOVIC Pavle	5	f	3	3	-1	12	2	0	0	0	0	0	4	1	1	1	2
701	31	11	THEIS Robert	5	f	1	0	-2	13	0	0	1	0	1	1	13	1	2	1	0
702	31	12	CONSTANTINOU Michai	5	f	16	5	-1	15	4	1	36	4	12	8	41	3	6	14	1
703	31	17	POLFER Felix	5	t	0	0	-4	0	0	0	18	4	6	4	0	0	0	0	0
704	31	22	BRISBOIS Nicolas	5	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
705	31	24	HAJ ISMAIL Mohamed	5	f	0	0	-1	3	1	0	0	0	0	0	0	0	0	0	0
706	31	27	COURRIOUX Quentin	5	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
707	31	77	DUDA Karol	5	f	8	3	7	5	0	0	1	0	1	1	9	0	1	5	3
708	31	82	LOMACZ Jakub	5	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
709	31	2	ARAPI Adri	8	f	1	1	1	6	0	0	0	0	0	0	0	0	0	0	1
710	31	3	QERRAXHIJA Klaudio	8	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
711	31	4	DATUS Moise	8	f	13	12	8	7	2	1	3	0	1	1	20	1	2	11	1
712	31	5	JUTTEL Mick	8	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
713	31	8	PAVELKA Tomas	8	f	9	2	4	9	1	0	20	2	9	6	18	1	1	9	0
714	31	9	ALAGIC Adonis	8	f	5	3	5	10	0	2	0	0	0	0	1	0	0	0	3
715	31	14	ZUIDBERG Chris	8	f	21	9	12	22	2	0	19	2	9	5	44	3	2	18	3
716	31	17	SONNET Francois	8	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
717	31	18	ZEHREN David	8	f	11	6	8	12	1	0	0	0	0	0	10	1	1	5	6
718	31	19	FISCHER Hugo	8	f	10	5	-2	18	3	1	2	2	0	0	25	5	2	7	2
719	31	21	KUHBERG Armin	8	f	4	3	1	19	3	1	0	0	0	0	2	0	0	1	2
720	31	22	JANSEN Miguel	8	t	0	0	-6	0	0	0	26	6	6	1	0	0	0	0	0
721	32	1	AUZANI Leonardo	2	f	7	3	5	16	1	0	0	0	0	0	10	1	0	6	1
722	32	2	MARINHO NOVAIS Sam	2	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
723	32	3	CALHOUN Cameron	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
724	32	4	MARINHO NOVAIS Sim	2	f	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0
725	32	5	MAGGIOLO Enzo	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
726	32	6	BRAAS Gilles	2	f	3	1	0	21	2	0	0	0	0	0	4	1	0	2	1
727	32	7	MILOSEVIC Boris	2	f	6	5	5	5	0	0	14	0	11	3	14	1	0	4	2
728	32	8	MATILDE DA LUZ Ryan	2	f	13	5	9	16	1	1	1	1	0	0	14	1	1	11	1
729	32	10	ARAB Sina	2	f	20	11	12	26	2	3	17	2	12	8	28	1	3	16	1
730	32	13	CZAPOR Leon Eric	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
731	32	14	HALDORSEN Jan	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
732	32	15	GAJIN Mareja	2	f	35	19	25	22	3	2	1	0	0	0	47	6	1	23	10
733	32	17	TOPALOV Todor	2	f	5	1	-2	4	0	0	11	2	5	4	15	1	4	5	0
734	32	23	GARBO Lorenzo	2	t	0	0	-4	0	0	0	35	4	20	13	0	0	0	0	0
735	32	1	SCHUBERT Jared	7	t	0	0	-2	0	0	0	30	2	19	12	0	0	0	0	0
736	32	2	KOLACNY Jaromir	7	f	21	5	13	16	0	1	0	0	0	0	46	3	5	18	2
737	32	4	KIFFER Max	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
738	32	5	LANDUYDT Olivier	7	f	2	0	-1	15	3	0	0	0	0	0	6	0	0	2	0
739	32	8	VARGAS Lyndon	7	f	11	2	7	12	2	1	2	1	1	1	11	0	1	9	1
740	32	9	WEBER Steve	7	f	11	6	-9	21	1	4	24	6	12	10	32	5	8	5	2
741	32	11	HILBERT Colin	7	f	5	2	-1	10	0	0	37	2	13	5	20	4	0	5	0
742	32	13	KRAMER Fynn	7	f	2	0	-1	2	1	0	6	0	3	1	5	0	2	2	0
743	32	14	RUBY Nicolas	7	f	2	2	1	2	1	1	0	0	0	0	3	0	0	0	1
744	32	16	BIBEL Akos	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
745	32	17	FUNK Max	7	f	7	5	6	8	1	0	1	0	1	0	6	0	0	4	3
746	32	21	ROBIN Gabriel	7	f	3	0	1	2	0	0	2	1	1	1	6	1	0	3	0
747	32	22	TONIC Nikola	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
748	32	24	SITAR HAFNER Dan	7	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
749	33	2	ARAPI Adri	8	f	0	0	0	4	0	0	0	0	0	0	1	0	0	0	0
750	33	3	QERRAXHIJA Klaudio	8	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
751	33	4	DATUS Moise	8	f	18	10	9	17	3	3	23	2	3	1	36	3	1	13	2
752	33	5	JUTTEL Mick	8	f	0	0	0	2	0	0	0	0	0	0	0	0	0	0	0
753	33	8	PAVELKA Tomas	8	f	4	1	0	5	1	0	13	1	2	1	10	2	0	4	0
754	33	9	ALAGIC Adonis	8	f	0	0	-4	15	4	0	0	0	0	0	2	0	0	0	0
755	33	14	ZUIDBERG Chris	8	f	13	4	7	9	0	0	16	3	7	3	26	2	1	11	2
756	33	16	GLESENER Philippe	8	t	0	0	-5	0	0	0	39	5	12	10	0	0	0	0	0
757	33	17	SONNET Francois	8	f	3	2	1	11	2	1	1	0	1	1	1	0	0	0	2
758	33	18	ZEHREN David	8	f	8	3	6	18	0	1	0	0	0	0	9	2	0	5	2
759	33	19	FISCHER Hugo	8	f	27	8	7	20	7	2	3	2	0	0	49	9	2	23	2
760	33	1	AUZANI Leonardo	2	f	5	2	2	12	1	0	0	0	0	0	11	2	0	5	0
761	33	2	MARINHO NOVAIS Sam	2	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
762	33	3	CALHOUN Cameron	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
763	33	4	MARINHO NOVAIS Sim	2	f	0	0	0	3	0	0	0	0	0	0	0	0	0	0	0
764	33	5	MAGGIOLO Enzo	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
765	33	6	BRAAS Gilles	2	f	3	2	-2	14	2	0	2	2	0	0	9	1	0	2	1
766	33	7	MILOSEVIC Boris	2	f	3	2	0	2	1	0	2	1	0	0	4	0	1	2	1
767	33	8	MATILDE DA LUZ Ryan	2	f	8	4	4	16	4	1	0	0	0	0	13	0	0	7	0
768	33	10	ARAB Sina	2	f	12	6	3	9	0	0	20	2	7	5	30	3	4	12	0
769	33	14	HALDORSEN Jan	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
770	33	15	GAJIN Mareja	2	f	25	12	14	28	4	3	0	0	0	0	44	4	3	22	0
771	33	17	TOPALOV Todor	2	f	16	7	5	24	1	3	21	7	3	2	21	1	2	11	2
772	33	23	GARBO Lorenzo	2	t	0	0	-4	0	0	0	39	4	14	9	0	0	0	0	0
773	34	1	SCHUBERT Jared	7	t	0	0	0	0	0	0	2	0	2	1	0	0	0	0	0
774	34	2	KOLACNY Jaromir	7	f	13	6	12	16	1	0	0	0	0	0	24	0	0	11	2
775	34	5	LANDUYDT Olivier	7	f	5	2	5	13	0	0	0	0	0	0	4	0	0	3	2
776	34	6	BARNES Issac	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
777	34	8	VARGAS Lyndon	7	f	5	3	5	6	0	0	0	0	0	0	2	0	0	2	3
778	34	9	WEBER Steve	7	f	12	9	7	9	2	3	8	0	2	2	17	2	1	8	1
779	34	11	HILBERT Colin	7	f	5	4	1	3	2	0	3	0	1	1	8	2	0	2	3
780	34	13	KRAMER Fynn	7	f	10	3	5	6	1	1	12	0	4	4	15	2	2	8	1
781	34	14	RUBY Nicolas	7	f	1	0	1	0	0	0	0	0	0	0	1	0	0	1	0
782	34	16	BIBEL Akos	7	f	3	2	2	3	0	0	7	0	2	1	13	1	0	3	0
783	34	17	FUNK Max	7	f	0	0	-1	7	1	0	0	0	0	0	1	0	0	0	0
784	34	21	ROBIN Gabriel	7	f	4	2	4	9	0	1	0	0	0	0	3	0	0	2	1
785	34	22	TONIC Nikola	7	f	0	0	-1	1	1	0	0	0	0	0	0	0	0	0	0
786	34	24	SITAR HAFNER Dan	7	t	0	0	-2	0	0	0	11	2	4	1	0	0	0	0	0
787	34	4	METZGER Loris	3	f	4	1	-4	5	1	0	11	3	2	0	19	3	1	4	0
788	34	7	NEME RODRIGUES Nad	3	f	5	0	2	5	0	0	2	0	1	1	13	1	2	5	0
789	34	8	BOLLENDORFF Pol	3	f	6	3	1	12	1	0	19	2	9	7	17	2	0	6	0
790	34	9	HIRTZ WEIS Sam	3	f	1	1	0	8	1	0	0	0	0	0	3	0	0	0	1
791	34	11	RZYMIANSKI Radoslaw	3	f	8	0	-3	7	1	0	3	1	1	1	30	2	7	8	0
792	34	14	WILDGEN Charel	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
793	34	18	OESCH Noah	3	f	4	1	0	4	1	1	0	0	0	0	14	0	3	3	0
794	34	23	STEIN Max	3	t	0	0	-5	0	0	0	30	5	8	5	0	0	0	0	0
795	34	44	MAZUR Marcel	3	f	3	2	0	10	3	0	0	0	0	0	5	0	0	1	2
796	35	1	HONORATO DE ALMEI	4	f	2	0	2	4	0	0	0	0	0	0	2	0	0	2	0
797	35	2	CAVALCANTI DE OLIVEI	4	f	0	0	0	10	0	0	0	0	0	0	1	0	0	0	0
798	35	3	MADEJ Maciej	4	f	9	5	7	3	0	0	0	0	0	0	16	1	1	8	1
799	35	4	MARECHAL Adrien	4	f	7	3	6	8	1	1	0	0	0	0	4	0	0	4	2
800	35	5	LOYOLA LAVIN Nelson	4	f	13	4	9	15	1	1	8	0	3	2	24	3	0	11	1
801	35	7	CLEEN Jules	4	f	3	2	0	5	1	1	0	0	0	0	6	1	1	2	0
802	35	8	HEIRENS Sony	4	f	0	0	-1	2	0	0	0	0	0	0	1	1	0	0	0
803	35	9	BEN TARA Sami	4	f	3	2	3	9	0	2	0	0	0	0	3	0	0	1	0
804	35	11	MANGEN Tim	4	f	6	4	2	6	1	1	0	0	0	0	6	3	0	3	2
805	35	13	MARECHAL Yann	4	t	0	0	0	0	0	0	18	0	5	3	0	0	0	0	0
806	35	14	MICHOTTE Arthur	4	f	3	2	1	4	1	1	2	0	1	0	9	1	0	2	0
807	35	18	MARETTE William	4	t	0	0	-1	0	0	0	12	1	7	4	0	0	0	0	0
808	35	19	HUKEL Jakub	4	f	9	4	3	8	3	0	7	0	5	5	14	2	1	9	0
809	35	1	WOLLES Sam	6	f	5	2	1	7	1	0	13	2	4	3	12	1	0	3	2
810	35	3	HINKEL Sam	6	f	1	0	0	3	0	0	1	1	0	0	2	0	0	1	0
811	35	5	EVEN Philippe	6	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
812	35	6	ENGELDINGER Tom	6	f	1	0	-2	9	1	0	0	0	0	0	5	2	0	1	0
813	35	7	Szturma Nicolas	6	f	7	2	0	10	0	0	15	4	3	2	18	1	2	7	0
814	35	9	WIRTZ Sam	6	f	7	3	4	4	0	0	0	0	0	0	15	2	1	6	1
815	35	10	THIES Joey	6	t	0	0	-5	0	0	0	26	5	9	6	0	0	0	0	0
816	35	11	HONG Joseph	6	f	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0
817	35	18	DZINIC Aziz	6	t	0	0	-3	0	0	0	10	3	1	1	0	0	0	0	0
818	35	19	BOLLENDORFF Frank	6	f	0	0	-3	0	0	0	0	0	0	0	5	2	1	0	0
819	35	55	WEIRIG Yann	6	f	3	0	1	4	0	0	0	0	0	0	6	1	1	3	0
820	35	69	BESCH Tim	6	f	1	0	-2	0	0	0	1	0	0	0	6	2	1	1	0
821	35	77	BETTI Raphael	6	f	0	0	-1	12	1	0	0	0	0	0	3	0	0	0	0
822	36	1	SCHUBERT Jared	7	t	0	0	-3	0	0	0	19	3	10	6	0	0	0	0	0
823	36	2	KOLACNY Jaromir	7	f	16	5	6	9	1	0	1	1	0	0	37	2	6	15	1
824	36	5	LANDUYDT Olivier	7	f	4	0	2	16	1	0	0	0	0	0	4	1	0	2	2
825	36	7	ESSELIN Mathis	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
826	36	8	VARGAS Lyndon	7	f	4	4	3	17	1	0	2	0	0	0	5	0	0	2	2
827	36	9	WEBER Steve	7	f	17	5	12	15	1	1	17	1	4	2	31	3	0	15	1
828	36	11	HILBERT Colin	7	f	25	14	15	14	5	1	38	1	18	10	33	0	4	19	5
829	36	13	KRAMER Fynn	7	f	0	0	-1	1	1	0	1	0	0	0	0	0	0	0	0
830	36	14	RUBY Nicolas	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
831	36	16	BIBEL Akos	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
832	36	17	FUNK Max	7	f	3	3	0	22	3	0	0	0	0	0	2	0	0	1	2
833	36	21	ROBIN Gabriel	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
834	36	22	TONIC Nikola	7	f	0	0	0	2	0	0	0	0	0	0	0	0	0	0	0
835	36	24	SITAR HAFNER Dan	7	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
836	36	1	HONORATO DE ALMEI	4	f	7	4	6	9	0	0	0	0	0	0	12	0	1	4	3
837	36	2	CAVALCANTI DE OLIVEI	4	f	0	0	-1	24	1	0	0	0	0	0	0	0	0	0	0
838	36	3	MADEJ Maciej	4	f	9	6	1	4	1	1	5	0	1	1	14	5	2	4	4
839	36	4	MARECHAL Adrien	4	f	5	3	5	12	0	3	0	0	0	0	3	0	0	2	0
840	36	5	LOYOLA LAVIN Nelson	4	f	11	2	4	10	1	1	35	0	19	10	26	5	1	9	1
841	36	6	GARCIA Pedro	4	f	16	7	3	8	3	0	0	0	0	0	33	6	4	15	1
842	36	7	CLEEN Jules	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
843	36	8	HEIRENS Sony	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
844	36	9	BEN TARA Sami	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
845	36	11	MANGEN Tim	4	f	1	0	0	8	1	0	0	0	0	0	5	0	0	1	0
846	36	14	MICHOTTE Arthur	4	f	1	0	0	2	0	0	5	1	2	0	1	0	0	1	0
847	36	16	MADEJ Jakub	4	t	0	0	-1	0	0	0	22	1	9	7	0	0	0	0	0
848	36	18	MARETTE William	4	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
849	36	19	HUKEL Jakub	4	f	15	5	6	11	3	0	16	0	7	4	27	1	5	14	1
850	37	2	MARINHO NOVAIS Sam	2	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
851	37	3	CALHOUN Cameron	2	f	15	7	6	10	4	1	0	0	0	0	25	3	2	11	3
852	37	4	MARINHO NOVAIS Sim	2	f	2	1	1	9	1	1	0	0	0	0	1	0	0	1	0
853	37	5	MAGGIOLO Enzo	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
854	37	6	BRAAS Gilles	2	f	3	3	2	8	1	1	0	0	0	0	0	0	0	0	2
855	37	7	MILOSEVIC Boris	2	f	6	5	5	3	0	0	4	1	0	0	10	0	0	6	0
856	37	8	MATILDE DA LUZ Ryan	2	f	8	2	4	13	2	0	0	0	0	0	8	2	0	6	2
857	37	9	INEMEK Louis	2	f	1	0	-1	0	0	0	1	1	0	0	2	1	0	1	0
858	37	10	ARAB Sina	2	f	12	6	11	9	0	0	10	0	5	4	15	0	1	12	0
859	37	13	CZAPOR Leon Eric	2	f	7	4	2	9	3	1	4	2	1	1	9	0	0	6	0
860	37	16	AUZANI Leonardo	2	f	4	3	2	10	2	0	0	0	0	0	5	0	0	2	2
861	37	17	TOPALOV Todor	2	f	1	0	-1	1	0	0	4	1	1	1	7	1	0	1	0
862	37	19	HALDORSEN Jan	2	f	2	1	2	2	0	1	0	0	0	0	2	0	0	1	0
863	37	23	GARBO Lorenzo	2	t	0	0	-1	0	0	0	20	1	11	7	0	0	0	0	0
864	37	1	WOLLES Sam	6	f	2	2	-4	8	0	1	15	2	2	2	11	1	3	1	0
865	37	3	HINKEL Sam	6	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
866	37	5	EVEN Philippe	6	f	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0
867	37	6	ENGELDINGER Tom	6	f	4	0	1	5	3	0	0	0	0	0	8	0	0	4	0
868	37	7	SZTURMA Nicolas	6	f	6	1	-4	14	1	1	21	6	6	3	16	1	2	4	1
869	37	9	WIRTZ Sam	6	f	7	1	-2	5	0	0	1	1	0	0	28	5	3	6	1
870	37	10	THIES Joey	6	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
871	37	11	HONG Joseph	6	f	0	0	-1	1	1	0	1	0	0	0	0	0	0	0	0
872	37	18	DZINIC Aziz	6	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
873	37	19	BOLLENDORFF Frank	6	f	1	0	1	2	0	0	0	0	0	0	1	0	0	1	0
874	37	55	WEIRIG Yann	6	f	4	1	3	9	0	0	0	0	0	0	9	0	1	4	0
875	37	69	BESCH Tim	6	t	0	0	-4	0	0	0	23	4	5	3	0	0	0	0	0
876	37	77	BETTI Raphael	6	f	2	2	0	4	1	0	0	0	0	0	6	1	0	1	1
877	38	1	AUZANI Leonardo	2	f	7	3	2	14	4	0	0	0	0	0	9	1	0	6	1
878	38	2	MARINHO NOVAIS Sam	2	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
879	38	3	CALHOUN Cameron	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
880	38	4	MARINHO NOVAIS Sim	2	f	0	0	0	2	0	0	0	0	0	0	0	0	0	0	0
881	38	5	MAGGIOLO Enzo	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
882	38	6	BRAAS Gilles	2	f	5	3	3	18	1	1	0	0	0	0	4	0	1	3	1
883	38	8	MATILDE DA LUZ Ryan	2	f	10	5	7	13	1	1	0	0	0	0	9	2	0	7	2
884	38	10	ARAB Sina	2	f	20	6	8	23	0	2	26	0	16	8	41	4	8	18	0
885	38	13	CZAPOR Leon Eric	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
886	38	14	HALDORSEN Jan	2	f	0	0	-1	1	1	0	0	0	0	0	0	0	0	0	0
887	38	15	GAJIN Mareja	2	f	24	12	10	16	4	1	1	0	1	1	44	4	6	19	4
888	38	17	TOPALOV Todor	2	f	14	2	5	22	2	0	22	3	4	3	23	1	3	12	2
889	38	23	GARBO Lorenzo	2	t	0	0	-1	0	0	0	31	1	11	7	0	0	0	0	0
890	38	2	ARAPI Adri	8	f	0	0	-1	2	1	0	0	0	0	0	0	0	0	0	0
891	38	3	QERRAXHIJA Klaudio	8	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
892	38	4	DATUS Moise	8	f	21	4	0	21	8	2	23	5	8	6	38	6	2	17	2
893	38	5	JUTTEL Mick	8	f	0	0	0	0	0	0	2	0	1	1	0	0	0	0	0
894	38	8	PAVELKA Tomas	8	f	6	2	2	8	0	1	20	2	6	0	12	0	2	4	1
895	38	9	ALAGIC Adonis	8	f	3	2	2	14	1	0	0	0	0	0	2	0	0	0	3
896	38	14	ZUIDBERG Chris	8	f	9	1	8	7	0	0	8	1	4	3	18	0	0	9	0
897	38	17	SONNET Francois	8	f	0	0	-1	0	0	0	0	0	0	0	1	1	0	0	0
898	38	18	ZEHREN David	8	f	6	3	4	14	1	0	1	0	0	0	6	0	1	2	4
899	38	19	FISCHER Hugo	8	f	23	6	10	16	4	0	2	0	2	1	42	5	4	15	8
900	38	21	KUHBERG Armin	8	f	2	1	-1	15	2	0	0	0	0	0	7	0	1	2	0
901	38	22	JANSEN Miguel	8	t	0	0	-3	0	0	0	40	3	19	16	0	0	0	0	0
902	39	2	ARAPI Adri	8	f	5	3	1	15	3	2	0	0	0	0	4	1	0	2	1
903	39	4	DATUS Moise	8	f	21	5	13	8	4	0	8	0	2	1	40	2	2	19	2
904	39	5	JUTTEL Mick	8	t	0	0	-1	0	0	0	24	1	6	2	0	0	0	0	0
905	39	8	PAVELKA Tomas	8	f	15	6	8	11	1	2	16	2	6	3	26	2	2	12	1
906	39	9	ALAGIC Adonis	8	f	0	0	0	3	0	0	0	0	0	0	0	0	0	0	0
907	39	14	ZUIDBERG Chris	8	f	1	0	-4	6	1	0	5	1	2	1	9	1	2	1	0
908	39	17	SONNET Francois	8	f	1	1	0	6	1	0	0	0	0	0	1	0	0	1	0
909	39	18	ZEHREN David	8	f	2	1	-2	17	2	0	0	0	0	0	7	0	2	1	1
910	39	19	FISCHER Hugo	8	f	8	3	1	7	3	0	17	1	8	6	16	0	3	5	3
911	39	21	KUHBERG Armin	8	f	5	4	2	7	3	1	0	0	0	0	6	0	0	3	1
912	39	22	JANSEN Miguel	8	t	0	0	0	0	0	0	7	0	2	1	0	0	0	0	0
913	39	1	SCHUBERT Jared	7	t	0	0	-3	0	0	0	18	3	6	4	0	0	0	0	0
914	39	2	KOLACNY Jaromir	7	f	16	7	8	17	2	1	0	0	0	0	38	2	4	12	3
915	39	5	LANDUYDT Olivier	7	f	5	2	3	18	2	0	0	0	0	0	6	0	0	3	2
916	39	7	ESSELIN Mathis	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
917	39	8	VARGAS Lyndon	7	f	6	4	5	10	0	0	0	0	0	0	7	1	0	5	1
918	39	9	WEBER Steve	7	f	16	6	7	13	2	0	17	3	6	3	31	3	1	13	3
919	39	11	HILBERT Colin	7	f	13	7	7	14	3	1	19	1	5	3	20	1	1	11	1
920	39	13	KRAMER Fynn	7	f	2	0	-4	1	1	0	8	1	1	1	8	1	3	2	0
921	39	14	RUBY Nicolas	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
922	39	16	BIBEL Akos	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
923	39	17	FUNK Max	7	f	2	2	1	15	1	1	0	0	0	0	1	0	0	0	1
924	39	21	ROBIN Gabriel	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
925	39	22	TONIC Nikola	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
926	39	24	SITAR HAFNER Dan	7	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
927	40	3	HINKEL Sam	6	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
928	40	5	EVEN Philippe	6	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
929	40	6	ENGELDINGER Tom	6	f	1	1	-2	6	2	0	0	0	0	0	9	1	0	1	0
930	40	7	SZTURMA Nicolas	6	f	11	2	3	11	0	0	12	3	4	4	26	2	3	10	1
931	40	9	WIRTZ Sam	6	f	8	4	1	10	2	0	0	0	0	0	26	4	1	8	0
932	40	10	THIES Joey	6	t	0	0	-6	0	0	0	39	6	7	0	0	0	0	0	0
933	40	11	HONG Joseph	6	f	0	0	-2	6	2	0	0	0	0	0	1	0	0	0	0
934	40	18	DZINIC Aziz	6	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
935	40	19	BOLLENDORFF Frank	6	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
936	40	55	WEIRIG Yann	6	f	4	2	-1	9	3	0	0	0	0	0	11	1	1	4	0
937	40	69	BESCH Tim	6	f	5	0	-2	11	1	0	12	3	4	2	16	3	0	4	1
938	40	77	BETTI Raphael	6	f	1	1	-2	3	3	0	0	0	0	0	2	0	0	1	0
939	40	1	SPEIDEL Karim	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
940	40	4	METZGER Loris	3	f	7	4	2	10	0	1	9	0	4	2	25	5	0	6	0
941	40	5	SANTER Philippe	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
942	40	6	ZENDER Christophe	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
943	40	7	NEME RODRIGUES Nad	3	f	8	3	7	19	1	2	1	0	0	0	9	0	0	5	1
944	40	8	BOLLENDORFF Pol	3	f	9	2	3	10	1	0	21	3	3	1	19	1	1	8	1
945	40	9	HIRTZ WEIS Sam	3	f	4	3	2	15	2	3	0	0	0	0	3	0	0	1	0
946	40	12	SINDECUSE Noah	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
947	40	17	DA SILVA MARQUES Ma	3	t	0	0	0	0	0	0	12	0	6	6	0	0	0	0	0
948	40	18	OESCH Noah	3	f	13	6	5	8	6	0	0	0	0	0	20	1	1	12	1
949	40	20	BUSSHUVEN Tim	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
950	40	23	STEIN Max	3	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
951	40	44	MAZUR Marcel	3	f	8	7	6	13	2	2	0	0	0	0	5	0	0	4	2
952	41	1	SCHUBERT Jared	7	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
953	41	2	KOLACNY Jaromir	7	f	16	11	14	8	2	1	0	0	0	0	21	0	0	13	2
954	41	4	KIFFER Max	7	f	5	5	4	2	1	0	0	0	0	0	6	0	0	4	1
955	41	5	LANDUYDT Olivier	7	f	8	7	7	19	1	4	0	0	0	0	3	0	0	2	2
956	41	8	VARGAS Lyndon	7	f	6	5	4	16	1	0	0	0	0	0	8	1	0	5	1
957	41	9	WEBER Steve	7	f	9	6	8	4	1	1	2	0	2	1	10	0	0	7	1
958	41	11	HILBERT Colin	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
959	41	13	KRAMER Fynn	7	f	9	4	5	14	2	1	13	1	3	0	13	1	0	8	0
960	41	14	RUBY Nicolas	7	f	5	2	2	4	1	0	4	0	2	0	11	1	1	5	0
961	41	17	FUNK Max	7	f	0	0	-1	1	1	0	0	0	0	0	0	0	0	0	0
962	41	22	TONIC Nikola	7	f	1	1	1	5	0	0	0	0	0	0	1	0	0	0	1
963	41	24	SITAR HAFNER Dan	7	t	0	0	0	0	0	0	4	0	0	0	0	0	0	0	0
964	41	3	WAGNER Victor	1	f	0	0	-1	5	1	0	1	0	0	0	0	0	0	0	0
965	41	4	BIVER Antoine	1	f	2	1	-1	5	1	1	1	1	0	0	7	1	0	1	0
966	41	5	SOMMERHALTER Vince	1	f	2	0	-4	3	1	0	4	1	1	1	18	2	2	2	0
967	41	10	HOFFMANN Maxime	1	f	4	1	2	3	0	0	2	1	0	0	13	0	1	3	1
968	41	16	LUMIA Yoan	1	t	0	0	-1	0	0	0	2	1	0	0	0	0	0	0	0
969	41	17	HANSEN Yann	1	f	2	0	0	4	0	0	11	1	6	3	7	0	1	2	0
970	41	28	DARROSA JANKOVIC Ni	1	f	1	0	-9	5	2	0	18	4	4	1	9	4	0	1	0
971	41	51	SANTOSI Peter	1	f	1	0	-8	4	1	0	24	4	13	9	11	0	4	1	0
972	42	1	NIZARD Gil	1	f	0	0	-1	7	0	0	0	0	0	0	1	1	0	0	0
973	42	3	WAGNER Victor	1	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
974	42	4	BIVER Antoine	1	f	1	0	-3	6	1	0	1	0	0	0	9	2	1	1	0
975	42	5	SOMMERHALTER Vince	1	f	8	0	-3	6	4	0	18	3	7	3	15	4	0	8	0
976	42	7	FELLINGER Felix	1	f	5	4	-6	8	2	0	0	0	0	0	26	6	3	5	0
977	42	10	HOFFMANN Maxime	1	f	4	1	2	4	1	0	0	0	0	0	8	1	0	3	1
978	42	28	DARROSA JANKOVIC Ni	1	f	5	3	-4	7	2	1	23	1	10	4	16	4	2	4	0
979	42	58	BARTH Frederic	1	t	0	0	-4	0	0	0	21	4	6	4	0	0	0	0	0
980	42	2	ARAPI Adri	8	f	0	0	0	3	0	0	0	0	0	0	0	0	0	0	0
981	42	4	DATUS Moise	8	f	7	4	4	4	2	0	1	0	0	0	12	1	0	5	2
982	42	5	JUTTEL Mick	8	t	0	0	-1	0	0	0	4	1	1	1	0	0	0	0	0
983	42	8	PAVELKA Tomas	8	f	11	5	9	9	0	1	8	0	2	1	19	1	1	10	0
984	42	9	ALAGIC Adonis	8	f	2	2	1	21	1	1	1	0	0	0	1	0	0	0	1
985	42	14	ZUIDBERG Chris	8	f	7	6	6	11	1	2	3	0	3	3	8	0	0	5	0
986	42	17	SONNET Francois	8	f	1	0	0	2	1	0	0	0	0	0	1	0	0	1	0
987	42	18	ZEHREN David	8	f	3	3	2	7	0	0	1	1	0	0	3	0	0	2	1
988	42	19	FISCHER Hugo	8	f	7	3	3	6	3	1	10	0	2	1	13	1	0	6	0
989	42	21	KUHBERG Armin	8	f	5	4	2	11	3	0	0	0	0	0	4	0	0	3	2
990	42	22	JANSEN Miguel	8	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
991	43	1	HONORATO DE ALMEI	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
992	43	2	CAVALCANTI DE OLIVEI	4	f	1	1	1	16	0	1	0	0	0	0	1	0	0	0	0
993	43	3	MADEJ Maciej	4	f	12	7	4	7	2	1	12	3	1	0	20	2	1	11	0
994	43	4	MARECHAL Adrien	4	f	6	4	3	9	1	0	0	0	0	0	9	1	1	5	1
995	43	5	LOYOLA LAVIN Nelson	4	f	4	1	2	4	0	0	8	0	5	3	9	1	1	4	0
996	43	6	GARCIA Pedro	4	f	8	4	6	6	1	0	0	0	0	0	14	0	1	8	0
997	43	7	CLEEN Jules	4	f	7	2	5	4	0	0	0	0	0	0	12	2	0	6	1
998	43	8	HEIRENS Sony	4	f	0	0	0	3	0	0	0	0	0	0	0	0	0	0	0
999	43	11	MANGEN Tim	4	f	6	4	4	9	2	1	0	0	0	0	4	0	0	3	2
1000	43	13	MARECHAL Yann	4	f	0	0	0	1	0	0	1	0	1	0	0	0	0	0	0
1001	43	14	MICHOTTE Arthur	4	f	4	2	1	7	1	1	7	0	1	0	12	2	0	3	0
1002	43	16	MADEJ Jakub	4	t	0	0	-1	0	0	0	11	1	5	1	0	0	0	0	0
1003	43	18	MARETTE William	4	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1004	43	19	HUKEL Jakub	4	f	7	4	6	7	0	1	5	0	3	2	14	1	0	6	0
1005	43	1	NIZARD Gil	1	f	1	1	0	5	1	1	0	0	0	0	0	0	0	0	0
1006	43	3	WAGNER Victor	1	f	1	1	1	6	0	1	0	0	0	0	1	0	0	0	0
1007	43	4	BIVER Antoine	1	f	1	0	0	8	1	0	0	0	0	0	7	0	0	1	0
1008	43	5	SOMMERHALTER Vince	1	f	5	1	-4	12	2	0	16	2	2	0	17	3	2	5	0
1009	43	7	FELLINGER Felix	1	f	10	3	5	7	2	1	0	0	0	0	32	2	1	7	2
1010	43	10	HOFFMANN Maxime	1	f	5	1	4	6	0	0	0	0	0	0	10	1	0	3	2
1011	43	15	VOSAHLO Frantisek	1	f	8	3	1	5	1	1	20	3	6	4	20	3	0	7	0
1012	43	28	DARROSA JANKOVIC Ni	1	f	0	0	-3	2	0	0	9	2	3	1	4	0	1	0	0
1013	43	58	BARTH Frederic	1	t	0	0	-3	0	0	0	21	3	11	9	0	0	0	0	0
1014	44	2	KOLACNY Jaromir	7	f	2	1	2	4	0	0	0	0	0	0	3	0	0	1	1
1015	44	4	KIFFER Max	7	f	1	1	0	6	1	0	0	0	0	0	0	0	0	0	1
1016	44	5	LANDUYDT Olivier	7	f	1	1	-1	3	2	0	0	0	0	0	3	0	0	0	1
1017	44	8	VARGAS Lyndon	7	f	9	6	8	11	1	0	0	0	0	0	6	0	0	5	4
1018	44	9	WEBER Steve	7	f	17	10	10	19	6	4	7	1	4	3	21	0	0	13	0
1019	44	11	HILBERT Colin	7	f	8	4	6	2	1	0	4	1	1	0	10	0	0	7	1
1020	44	13	KRAMER Fynn	7	f	7	3	5	6	1	0	10	0	5	2	14	0	1	6	1
1021	44	14	RUBY Nicolas	7	f	7	2	4	8	1	1	0	0	0	0	13	1	1	5	1
1022	44	16	BIBEL Akos	7	t	0	0	0	0	0	0	8	0	2	1	0	0	0	0	0
1023	44	17	FUNK Max	7	f	2	1	1	5	1	1	0	0	0	0	2	0	0	1	0
1024	44	21	ROBIN Gabriel	7	f	4	2	2	8	1	0	0	0	0	0	5	0	1	3	1
1025	44	22	TONIC Nikola	7	f	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0
1026	44	24	SITAR HAFNER Dan	7	t	0	0	-1	0	0	0	13	1	3	2	0	0	0	0	0
1027	44	1	WOLLES Sam	6	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1028	44	6	ENGELDINGER Tom	6	f	7	2	5	8	1	0	0	0	0	0	12	0	1	6	1
1029	44	7	SZTURMA Nicolas	6	f	5	1	-4	7	0	0	19	5	5	4	17	2	2	4	1
1030	44	9	WIRTZ Sam	6	f	4	1	-3	7	2	1	0	0	0	0	19	1	4	3	0
1031	44	10	THIES Joey	6	t	0	0	-5	0	0	0	18	5	3	2	0	0	0	0	0
1032	44	11	HONG Joseph	6	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1033	44	18	DZINIC Aziz	6	f	0	0	-2	1	1	0	0	0	0	0	1	1	0	0	0
1034	44	19	BOLLENDORFF Frank	6	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1035	44	55	WEIRIG Yann	6	f	6	2	3	8	1	1	0	0	0	0	16	0	2	4	1
1036	44	69	BESCH Tim	6	f	4	1	-2	7	0	0	21	1	2	0	14	3	2	4	0
1037	44	77	BETTI Raphael	6	f	2	0	0	10	1	0	0	0	0	0	4	1	0	2	0
1038	45	1	SCHUBERT Jared	7	t	0	0	0	0	0	0	20	0	8	2	0	0	0	0	0
1039	45	2	KOLACNY Jaromir	7	f	33	14	26	18	3	0	0	0	0	0	41	2	2	22	11
1040	45	4	KIFFER Max	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1041	45	5	LANDUYDT Olivier	7	f	3	2	2	14	1	0	0	0	0	0	5	0	0	1	2
1042	45	8	VARGAS Lyndon	7	f	5	2	3	10	1	0	0	0	0	0	13	1	0	5	0
1043	45	9	WEBER Steve	7	f	18	6	9	15	1	0	43	4	13	7	42	3	1	15	3
1044	45	11	HILBERT Colin	7	f	7	4	-8	17	2	0	22	4	9	4	27	6	3	6	1
1045	45	13	KRAMER Fynn	7	f	1	0	0	3	1	0	1	0	0	0	1	0	0	1	0
1046	45	14	RUBY Nicolas	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1047	45	16	BIBEL Akos	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1048	45	17	FUNK Max	7	f	2	1	1	21	1	0	1	0	0	0	4	0	0	2	0
1049	45	21	ROBIN Gabriel	7	f	7	1	5	10	2	0	0	0	0	0	5	0	0	5	2
1050	45	22	TONIC Nikola	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1051	45	24	SITAR HAFNER Dan	7	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1052	45	1	AUZANI Leonardo	2	f	14	3	10	18	2	1	1	0	0	0	17	1	1	12	1
1053	45	2	MARINHO NOVAIS Sam	2	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1054	45	3	CALHOUN Cameron	2	f	16	7	6	17	4	3	0	0	0	0	37	1	5	12	1
1055	45	4	MARINHO NOVAIS Sim	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1056	45	5	MAGGIOLO Enzo	2	f	3	1	-2	2	1	0	0	0	0	0	7	4	0	2	1
1057	45	6	BRAAS Gilles	2	f	6	4	4	20	2	1	0	0	0	0	7	0	0	4	1
1058	45	7	MILOSEVIC Boris	2	f	8	2	0	17	1	0	27	1	11	8	21	1	5	7	1
1059	45	8	MATILDE DA LUZ Ryan	2	f	10	0	2	15	4	0	0	0	0	0	18	4	0	10	0
1060	45	9	INEMEK Louis	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1061	45	10	ARAB Sina	2	f	18	4	8	12	2	0	21	2	14	9	42	1	5	17	1
1062	45	13	CZAPOR Leon Eric	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1063	45	14	HALDORSEN Jan	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1064	45	17	TOPALOV Todor	2	f	1	0	-2	2	0	0	5	0	2	1	4	0	3	1	0
1065	45	23	GARBO Lorenzo	2	t	0	0	-3	0	0	0	42	3	18	11	0	0	0	0	0
1066	46	1	WOLLES Sam	6	f	2	1	-8	8	1	0	35	8	11	8	12	0	1	1	1
1067	46	3	HINKEL Sam	6	f	2	1	1	2	0	0	0	0	0	0	5	1	0	2	0
1068	46	5	EVEN Philippe	6	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1069	46	6	ENGELDINGER Tom	6	f	5	0	3	7	0	0	1	1	0	0	7	1	0	4	1
1070	46	7	SZTURMA Nicolas	6	f	8	2	3	11	0	2	13	2	6	5	13	1	2	6	0
1071	46	9	WIRTZ Sam	6	f	5	1	1	6	1	0	0	0	0	0	18	2	1	5	0
1072	46	10	THIES Joey	6	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1073	46	11	HONG Joseph	6	f	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0
1074	46	18	DZINIC Aziz	6	f	0	0	0	0	0	0	1	0	0	0	0	0	0	0	0
1075	46	19	BOLLENDORFF Frank	6	f	1	0	1	0	0	0	0	0	0	0	1	0	0	1	0
1076	46	55	WEIRIG Yann	6	f	5	2	2	7	0	0	0	0	0	0	11	3	0	4	1
1077	46	69	BESCH Tim	6	t	0	0	-2	0	0	0	15	2	4	2	0	0	0	0	0
1078	46	77	BETTI Raphael	6	f	1	0	-1	8	1	0	0	0	0	0	7	1	0	1	0
1079	46	2	ARAPI Adri	8	f	6	6	4	13	2	5	0	0	0	0	0	0	0	0	1
1080	46	4	DATUS Moise	8	f	17	6	10	5	2	0	0	0	0	0	27	5	0	16	1
1081	46	5	JUTTEL Mick	8	t	0	0	-4	0	0	0	11	4	2	1	0	0	0	0	0
1082	46	8	PAVELKA Tomas	8	f	5	3	4	5	1	0	4	0	3	3	5	0	0	4	1
1083	46	9	ALAGIC Adonis	8	f	1	1	0	5	1	0	0	0	0	0	0	0	0	0	1
1084	46	14	ZUIDBERG Chris	8	f	14	6	10	14	0	1	10	0	7	6	22	2	2	13	0
1085	46	17	SONNET Francois	8	f	3	2	1	6	1	1	0	0	0	0	5	0	1	2	0
1086	46	18	ZEHREN David	8	f	5	1	4	14	1	1	0	0	0	0	4	0	0	4	0
1087	46	19	FISCHER Hugo	8	f	8	2	8	6	0	1	7	0	3	2	9	0	0	7	0
1088	46	21	KUHBERG Armin	8	f	3	1	2	6	1	0	0	0	0	0	5	0	0	3	0
1089	46	22	JANSEN Miguel	8	t	0	0	-1	0	0	0	15	1	9	4	0	0	0	0	0
1090	47	1	SPEIDEL Karim	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1091	47	4	METZGER Loris	3	f	5	1	0	5	0	0	18	2	3	2	10	2	1	3	2
1092	47	6	ZENDER Christophe	3	f	4	1	4	4	0	1	0	0	0	0	6	0	0	3	0
1093	47	7	NEME RODRIGUES Nad	3	f	10	2	6	11	2	1	2	1	0	0	14	0	1	9	0
1094	47	8	BOLLENDORFF Pol	3	f	3	0	-5	5	2	0	12	2	3	1	13	0	4	3	0
1095	47	9	HIRTZ WEIS Sam	3	f	8	4	6	14	2	2	0	0	0	0	5	0	0	3	3
1096	47	11	RZYMIANSKI Radoslaw	3	f	15	5	-4	14	2	1	29	2	16	9	41	8	7	13	1
1097	47	14	WILDGEN Charel	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1098	47	17	DA SILVA MARQUES Ma	3	t	0	0	-5	0	0	0	28	5	12	7	0	0	0	0	0
1099	47	18	OESCH Noah	3	f	9	2	3	5	3	0	0	0	0	0	22	3	0	9	0
1100	47	23	STEIN Max	3	t	0	0	0	0	0	0	2	0	1	0	0	0	0	0	0
1101	47	44	MAZUR Marcel	3	f	1	0	-1	13	2	0	0	0	0	0	2	0	0	1	0
1102	47	1	AUZANI Leonardo	2	f	9	5	7	13	0	1	0	0	0	0	10	1	1	7	1
1103	47	2	MARINHO NOVAIS Sam	2	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1104	47	4	MARINHO NOVAIS Sim	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1105	47	5	MAGGIOLO Enzo	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1106	47	6	BRAAS Gilles	2	f	7	6	7	18	0	1	0	0	0	0	4	0	0	1	5
1107	47	7	MILOSEVIC Boris	2	f	7	3	5	7	0	2	10	2	4	1	8	0	0	4	1
1108	47	8	MATILDE DA LUZ Ryan	2	f	9	5	4	12	1	0	4	1	1	1	11	3	0	8	1
1109	47	9	INEMEK Louis	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1110	47	10	ARAB Sina	2	f	10	6	6	12	1	0	13	1	7	5	18	0	2	10	0
1111	47	13	CZAPOR Leon Eric	2	f	1	0	0	2	0	0	5	1	2	0	1	0	0	1	0
1112	47	14	HALDORSEN Jan	2	f	1	1	1	5	0	0	0	0	0	0	1	0	0	0	1
1113	47	15	GAJIN Mareja	2	f	19	9	13	20	2	4	0	0	0	0	25	1	3	11	4
1114	47	17	TOPALOV Todor	2	f	6	2	2	8	2	0	16	1	7	2	12	1	0	6	0
1115	47	23	GARBO Lorenzo	2	t	0	0	-2	0	0	0	10	2	6	4	0	0	0	0	0
1116	48	1	DEINEGA Vladimir	5	f	7	0	0	10	2	0	8	1	3	3	19	2	2	6	1
1117	48	3	DOBRE Sebastian	5	f	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0
1118	48	8	BILAN Filip	5	f	7	3	2	3	2	0	0	0	0	0	9	1	2	6	1
1119	48	9	VUJOVIC Pavle	5	f	1	0	-1	8	2	0	0	0	0	0	4	0	0	1	0
1120	48	11	THEIS Robert	5	f	2	0	-1	9	1	0	1	1	0	0	7	1	0	2	0
1121	48	12	CONSTANTINOU Michai	5	f	11	3	3	7	3	1	10	1	4	2	21	2	2	10	0
1122	48	17	COURRIOUX Quentin	5	t	0	0	-7	0	0	0	35	7	14	11	0	0	0	0	0
1123	48	24	HAJ ISMAIL Mohamed	5	f	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0
1124	48	77	DUDA Karol	5	f	2	1	1	5	0	0	0	0	0	0	5	1	0	1	1
1125	48	82	LOMACZ Jakub	5	f	3	1	-4	6	4	0	9	1	4	2	12	0	2	3	0
1126	48	1	SCHUBERT Jared	7	t	0	0	0	0	0	0	3	0	1	1	0	0	0	0	0
1127	48	2	KOLACNY Jaromir	7	f	11	5	10	17	0	2	0	0	0	0	17	0	1	8	1
1128	48	4	KIFFER Max	7	f	1	1	1	0	0	0	0	0	0	0	1	0	0	1	0
1129	48	5	LANDUYDT Olivier	7	f	3	1	1	5	2	1	0	0	0	0	2	0	0	2	0
1130	48	8	VARGAS Lyndon	7	f	7	3	6	16	1	0	0	0	0	0	8	0	0	5	2
1131	48	9	WEBER Steve	7	f	12	6	7	8	2	0	18	1	9	4	20	1	1	10	2
1132	48	11	HILBERT Colin	7	f	6	3	5	3	1	0	5	0	3	2	7	0	0	5	1
1133	48	13	KRAMER Fynn	7	f	5	2	1	7	1	0	10	2	3	3	7	1	0	5	0
1134	48	14	RUBY Nicolas	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1135	48	16	BIBEL Akos	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1136	48	17	FUNK Max	7	f	2	2	0	7	1	2	0	0	0	0	1	0	1	0	0
1137	48	21	ROBIN Gabriel	7	f	3	2	1	6	2	1	0	0	0	0	1	0	0	1	1
1138	48	22	TONIC Nikola	7	f	1	0	1	4	0	0	0	0	0	0	1	0	0	1	1
1139	48	24	SITAR HAFNER Dan	7	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1140	49	1	DEINEGA Vladimir	5	f	13	5	9	14	1	2	0	0	0	0	25	3	0	11	0
1141	49	3	DOBRE Sebastian	5	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1142	49	4	MIRINKOVIC Luka	5	f	7	5	7	11	0	2	0	0	0	0	6	0	0	3	2
1143	49	8	BILAN Filip	5	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1144	49	9	VUJOVIC Pavle	5	f	4	1	2	13	2	0	1	0	0	0	4	0	0	4	0
1145	49	12	CONSTANTINOU Micha	5	f	8	3	-4	13	2	0	29	6	11	4	16	3	1	8	0
1146	49	17	POLFER Felix	5	t	0	0	-1	0	0	0	10	1	5	2	0	0	0	0	0
1147	49	24	HAJ ISMAIL Mohamed	5	f	0	0	-2	4	2	0	0	0	0	0	0	0	0	0	0
1148	49	77	DUDA Karol	5	f	3	1	2	6	0	0	0	0	0	0	5	0	1	1	3
1149	49	82	LOMACZ Jakub	5	f	7	5	-2	12	5	0	8	0	2	2	22	1	3	7	1
1150	49	1	SPEIDEL Karim	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1151	49	4	METZGER Loris	3	f	6	3	-3	7	1	1	18	3	5	3	12	4	1	4	1
1152	49	5	SANTER Philippe	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1153	49	6	ZENDER Christophe	3	f	7	2	6	9	0	0	8	0	3	0	12	1	0	7	0
1154	49	7	NEME RODRIGUES Nad	3	f	2	0	0	7	0	0	0	0	0	0	11	1	1	2	1
1155	49	8	BOLLENDORFF Pol	3	f	7	3	-2	7	1	0	19	2	7	4	28	4	2	6	1
1156	49	9	HIRTZ WEIS Sam	3	f	3	1	-2	7	3	0	1	0	0	0	6	1	1	2	1
1157	49	12	SINDECUSE Noah	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1158	49	17	DA SILVA MARQUES Ma	3	t	0	0	-4	0	0	0	15	4	4	2	0	0	0	0	0
1159	49	18	OESCH Noah	3	f	5	4	-2	9	1	1	0	0	0	0	18	6	0	3	1
1160	49	19	DIAS AMORIM Daniel	3	f	0	0	-1	1	1	0	0	0	0	0	0	0	0	0	0
1161	49	20	BUSSHUVEN Tim	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1162	49	23	STEIN Max	3	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1163	49	44	MAZUR Marcel	3	f	2	1	-3	11	3	0	0	0	0	0	4	1	1	2	0
1164	50	1	DEINEGA Vladimir	5	f	6	2	1	9	2	0	0	0	0	0	22	2	1	6	0
1165	50	3	DOBRE Sebastian	5	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1166	50	4	MIRINKOVIC Luka	5	f	4	0	-1	11	2	0	1	0	0	0	12	2	1	4	0
1167	50	9	VUJOVIC Pavle	5	f	1	1	0	9	1	1	2	0	1	0	1	0	0	0	0
1168	50	11	THEIS Robert	5	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1169	50	12	CONSTANTINOU Micha	5	f	3	0	-11	9	4	0	19	4	2	1	22	3	3	2	1
1170	50	17	POLFER Felix	5	t	0	0	-4	0	0	0	20	4	1	1	0	0	0	0	0
1171	50	24	HAJ ISMAIL Mohamed	5	f	0	0	0	3	0	0	0	0	0	0	0	0	0	0	0
1172	50	77	DUDA Karol	5	f	5	1	5	3	0	0	0	0	0	0	7	0	0	2	3
1173	50	82	LOMACZ Jakub	5	f	9	2	0	10	3	1	21	3	9	5	19	1	2	8	0
1174	50	2	MARINHO NOVAIS Sam	2	t	0	0	0	0	0	0	5	0	3	2	0	0	0	0	0
1175	50	3	CALHOUN Cameron	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1176	50	4	MARINHO NOVAIS Sim	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1177	50	5	MAGGIOLO Enzo	2	f	13	7	4	8	3	0	0	0	0	0	23	4	2	11	2
1178	50	6	BRAAS Gilles	2	f	6	3	4	20	2	3	1	0	0	0	4	0	0	2	2
1179	50	7	MILOSEVIC Boris	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1180	50	8	MATILDE DA LUZ Ryan	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1181	50	10	ARAB Sina	2	f	10	6	8	12	0	1	12	0	8	5	19	1	1	8	1
1182	50	13	CZAPOR Leon Eric	2	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1183	50	16	AUZANI Leonardo	2	f	6	3	4	8	1	0	0	0	0	0	10	1	0	4	2
1184	50	17	TOPALOV Todor	2	f	13	7	6	10	1	0	11	1	5	3	25	4	1	13	0
1185	50	19	HALDORSEN Jan	2	f	5	1	3	14	2	1	0	0	0	0	6	0	0	4	0
1186	50	23	GARBO Lorenzo	2	t	0	0	-3	0	0	0	13	3	5	2	0	0	0	0	0
1187	51	1	HONORATO DE ALMEID	4	f	6	4	5	14	0	1	1	0	0	0	8	0	1	3	2
1188	51	2	CAVALCANTI DE OLIVEI	4	f	0	0	0	12	0	0	0	0	0	0	3	0	0	0	0
1189	51	3	MADEJ Maciej	4	f	14	5	5	13	3	2	18	4	3	2	23	0	2	9	3
1190	51	4	MARECHAL Adrien	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1191	51	5	LOYOLA LAVIN Nelson	4	f	15	5	8	14	3	1	14	0	2	2	26	3	1	13	1
1192	51	6	GARCIA Pedro	4	f	17	3	3	16	6	2	0	0	0	0	33	6	2	15	0
1193	51	11	MANGEN Tim	4	f	5	3	2	14	2	2	0	0	0	0	5	1	0	2	2
1194	51	12	MEYERS Dan	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1195	51	13	MARECHAL Yann	4	f	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0
1196	51	14	MICHOTTE Arthur	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1197	51	16	MADEJ Jakub	4	t	0	0	-5	0	0	0	34	5	8	5	0	0	0	0	0
1198	51	18	MARETTE William	4	t	0	0	0	0	0	0	1	0	0	0	0	0	0	0	0
1199	51	19	HUKEL Jakub	4	f	2	1	-6	8	1	1	10	3	2	2	9	1	3	1	0
1200	51	2	ARAPI Adri	8	f	4	1	1	6	2	0	0	0	0	0	6	1	0	4	0
1201	51	3	QERRAXHIJA Klaudio	8	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1202	51	4	DATUS Moise	8	f	17	6	1	13	5	1	18	5	4	3	32	5	1	16	0
1203	51	5	JUTTEL Mick	8	f	0	0	-2	2	1	0	0	0	0	0	2	0	1	0	0
1204	51	8	PAVELKA Tomas	8	f	3	2	2	3	0	1	4	0	0	0	3	1	0	1	1
1205	51	9	ALAGIC Adonis	8	f	1	1	1	9	0	0	0	0	0	0	0	0	0	0	1
1206	51	14	ZUIDBERG Chris	8	f	13	2	5	17	1	1	32	4	20	18	24	1	2	11	1
1207	51	16	GLESENER Philippe	8	t	0	0	-3	0	0	0	16	3	5	3	0	0	0	0	0
1208	51	17	SONNET Francois	8	f	8	7	7	14	0	2	1	1	0	0	6	0	0	3	3
1209	51	18	ZEHREN David	8	f	5	3	2	15	0	0	2	1	1	0	9	2	0	2	3
1210	51	19	FISCHER Hugo	8	f	14	2	-1	12	4	1	4	1	0	0	32	6	4	13	0
1211	51	22	JANSEN Miguel	8	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1212	52	2	ARAPI Adri	8	f	3	2	1	5	2	0	0	0	0	0	3	0	0	2	1
1213	52	3	QERRAXHIJA Klaudio	8	f	2	2	0	0	0	0	2	2	0	0	2	0	0	1	1
1214	52	4	DATUS Moise	8	f	22	14	18	19	4	5	9	0	0	0	20	0	0	17	0
1215	52	5	JUTTEL Mick	8	f	2	2	2	0	0	0	0	0	0	0	3	0	0	1	1
1216	52	8	PAVELKA Tomas	8	f	1	0	0	6	0	0	3	0	1	1	5	0	1	1	0
1217	52	9	ALAGIC Adonis	8	f	3	3	2	12	1	1	0	0	0	0	0	0	0	0	2
1218	52	14	ZUIDBERG Chris	8	f	8	5	6	5	1	0	2	1	1	0	9	0	0	8	0
1219	52	16	GLESENER Philippe	8	t	0	0	-1	0	0	0	8	1	5	3	0	0	0	0	0
1220	52	17	SONNET Francois	8	f	5	3	5	8	0	1	0	0	0	0	3	0	0	3	1
1221	52	18	ZEHREN David	8	f	6	6	6	9	0	1	1	0	1	0	4	0	0	4	1
1222	52	19	FISCHER Hugo	8	f	12	6	8	10	2	2	2	0	0	0	16	1	1	9	1
1223	52	22	JANSEN Miguel	8	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1224	52	1	NIZARD Gil	1	f	0	0	-1	3	1	0	0	0	0	0	0	0	0	0	0
1225	52	2	BIVER Antoine	1	f	4	1	3	6	1	0	0	0	0	0	7	0	0	4	0
1226	52	3	WAGNER Victor	1	f	0	0	-2	3	1	0	0	0	0	0	2	0	1	0	0
1227	52	4	LUMIA Yoan	1	t	0	0	-10	0	0	0	16	10	1	1	0	0	0	0	0
1228	52	5	SOMMERHALTER Vince	1	f	3	0	-4	5	0	0	20	4	6	3	8	1	2	3	0
1229	52	9	SANTOSI Peter	1	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1230	52	10	HOFFMANN Maxime	1	f	4	1	2	4	0	0	2	2	0	0	5	0	0	3	1
1231	52	13	FELLINGER Felix	1	f	1	0	-11	5	1	0	17	6	4	3	15	4	1	1	0
1232	52	28	DARROSA JANKOVIC Ni	1	f	8	4	-1	6	1	2	9	4	3	2	14	0	4	5	1
1233	53	1	HONORATO DE ALMEID	4	f	12	6	10	15	0	1	0	0	0	0	15	1	1	10	1
1234	53	2	CAVALCANTI DE OLIVEI	4	f	0	0	-1	16	1	0	0	0	0	0	1	0	0	0	0
1235	53	3	MADEJ Maciej	4	f	1	1	0	1	1	0	0	0	0	0	3	0	0	0	1
1236	53	4	MARECHAL Adrien	4	f	3	0	0	8	2	0	0	0	0	0	7	0	1	3	0
1237	53	5	LOYOLA LAVIN Nelson	4	f	24	11	14	12	3	0	42	3	22	11	35	1	3	21	3
1238	53	6	GARCIA Pedro	4	f	16	0	-3	14	3	0	2	0	0	0	41	6	10	16	0
1239	53	7	CLEES Jules	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1240	53	11	MANGEN Tim	4	f	2	1	1	6	1	0	0	0	0	0	2	0	0	2	0
1241	53	13	MARECHAL Yann	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1242	53	16	MADEJ Jakub	4	t	0	0	-2	0	0	0	22	2	9	6	0	0	0	0	0
1243	53	18	MARETTE William	4	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1244	53	19	HUKEL Jakub	4	f	11	3	-4	19	4	0	23	4	8	6	30	4	3	9	2
1245	53	1	SCHUBERT Jared	7	t	0	0	-1	0	0	0	11	1	5	1	0	0	0	0	0
1246	53	2	KOLACNY Jaromir	7	f	17	3	11	17	1	1	0	0	0	0	32	1	4	14	2
1247	53	4	KIFFER Max	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1248	53	5	LANDUYDT Olivier	7	f	7	3	5	18	1	0	0	0	0	0	5	1	0	4	3
1249	53	8	VARGAS Lyndon	7	f	10	5	10	13	0	0	0	0	0	0	9	0	0	5	5
1250	53	9	WEBER Steve	7	f	17	8	7	25	1	3	23	2	13	8	30	6	1	12	2
1251	53	11	HILBERT Colin	7	f	16	8	5	13	3	1	41	5	16	5	22	1	2	10	5
1252	53	13	KRAMER Fynn	7	f	0	0	-1	1	1	0	0	0	0	0	0	0	0	0	0
1253	53	14	RUBY Nicolas	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1254	53	17	FUNK Max	7	f	2	1	1	10	1	0	0	0	0	0	2	0	0	1	1
1255	53	22	TONIC Nikola	7	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1256	54	1	WOLLES Sam	6	f	1	0	-3	4	0	0	10	3	2	0	3	0	1	1	0
1257	54	3	HINKEL Sam	6	f	0	0	-2	3	1	0	1	1	0	0	0	0	0	0	0
1258	54	6	ENGELDINGER Tom	6	f	5	1	2	9	2	0	0	0	0	0	8	0	1	3	2
1259	54	7	SZTURMA Nicolas	6	f	5	0	-5	7	1	0	9	4	3	0	24	3	2	5	0
1260	54	10	THIES Joey	6	t	0	0	-6	0	0	0	22	6	1	0	0	0	0	0	0
1261	54	11	HONG Joseph	6	f	0	0	-2	2	2	0	1	0	0	0	2	0	0	0	0
1262	54	18	DZINIC Aziz	6	f	2	0	-1	5	1	0	0	0	0	0	6	1	1	2	0
1263	54	55	WEIRIG Yann	6	f	3	1	0	3	1	0	0	0	0	0	9	1	1	2	1
1264	54	69	BESCH Tim	6	f	1	0	-4	4	2	0	17	2	7	3	4	1	0	1	0
1265	54	77	BETTI Raphael	6	f	2	0	1	5	1	0	0	0	0	0	2	0	0	2	0
1266	54	1	HONORATO DE ALMEID	4	f	0	0	-1	8	1	0	0	0	0	0	0	0	0	0	0
1267	54	2	CAVALCANTI DE OLIVEI	4	f	2	2	1	20	1	2	0	0	0	0	1	0	0	0	1
1268	54	3	MADEJ Maciej	4	f	12	4	4	6	3	0	7	0	0	0	21	2	3	12	0
1269	54	4	MARECHAL Adrien	4	f	8	5	5	11	2	3	0	0	0	0	8	1	0	3	2
1270	54	5	LOYOLA LAVIN Nelson	4	f	17	8	16	13	0	4	6	0	3	3	15	1	0	13	0
1271	54	6	GARCIA Pedro	4	f	7	4	1	5	4	1	0	0	0	0	9	2	0	5	1
1272	54	7	CLEES Jules	4	f	5	5	5	2	0	1	0	0	0	0	4	0	0	3	1
1273	54	11	MANGEN Tim	4	f	3	3	0	8	2	1	0	0	0	0	5	1	0	1	1
1274	54	16	MADEJ Jakub	4	t	0	0	-2	0	0	0	16	2	8	4	0	0	0	0	0
1275	54	18	MARETTE William	4	t	0	0	0	0	0	0	2	0	2	2	0	0	0	0	0
1276	54	19	HUKEL Jakub	4	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1277	55	1	SPEIDEL Karim	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1278	55	4	METZGER Loris	3	f	18	11	5	16	3	4	11	3	3	3	30	4	3	14	0
1279	55	6	ZENDER Christophe	3	f	5	3	3	11	1	1	0	0	0	0	11	0	1	4	0
1280	55	7	NEME RODRIGUES Nad	3	f	9	5	8	11	1	2	0	0	0	0	7	0	0	6	1
1281	55	8	BOLLENDORFF Pol	3	f	8	5	5	9	1	1	6	1	1	0	17	1	0	6	1
1282	55	9	HIRTZ WEIS Sam	3	f	7	1	6	9	1	0	1	0	0	0	9	0	0	5	2
1283	55	12	SINDECUSE Noah	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1284	55	14	WILDGEN Charel	3	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1285	55	17	DA SILVA MARQUES Ma	3	t	0	0	0	0	0	0	10	0	7	4	0	0	0	0	0
1286	55	18	OESCH Noah	3	f	3	2	0	3	0	0	0	0	0	0	7	2	1	3	0
1287	55	23	STEIN Max	3	t	0	0	-2	0	0	0	14	2	5	2	0	0	0	0	0
1288	55	44	MAZUR Marcel	3	f	6	4	1	15	4	1	0	0	0	0	4	1	0	2	3
1289	55	1	WOLLES Sam	6	f	0	0	-7	5	1	0	9	2	2	2	8	1	3	0	0
1290	55	3	HINKEL Sam	6	f	0	0	-1	1	1	0	0	0	0	0	1	0	0	0	0
1291	55	5	EVEN Philippe	6	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1292	55	6	ENGELDINGER Tom	6	f	8	3	3	17	2	2	1	1	0	0	14	2	0	5	1
1293	55	7	SZTURMA Nicolas	6	f	9	5	0	6	2	0	27	5	7	5	25	0	2	9	1
1294	55	10	THIES Joey	6	t	0	0	-6	0	0	0	18	6	2	2	0	0	0	0	0
1295	55	11	HONG Joseph	6	f	0	0	0	0	0	0	0	0	0	0	1	0	0	0	0
1296	55	18	DZINIC Aziz	6	f	3	0	2	2	1	0	0	0	0	0	5	0	0	3	0
1297	55	19	BOLLENDORFF Frank	6	f	1	1	-3	7	1	1	0	0	0	0	5	1	2	0	0
1298	55	55	WEIRIG Yann	6	f	3	1	1	4	1	0	0	0	0	0	6	1	0	2	2
1299	55	69	BESCH Tim	6	f	3	0	-2	3	1	0	8	3	2	2	6	1	0	3	0
1300	55	77	BETTI Raphael	6	f	3	2	0	8	1	0	0	0	0	0	9	2	0	2	1
1301	56	1	WOLLES Sam	6	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1302	56	3	HINKEL Sam	6	f	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1303	56	5	EVEN Philippe	6	t	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1304	56	6	ENGELDINGER Tom	6	f	10	6	6	15	2	2	1	0	0	0	12	2	0	6	3
1305	56	7	SZTURMA Nicolas	6	f	13	6	11	14	0	0	7	0	1	0	25	0	2	12	1
1306	56	9	WIRTZ Sam	6	f	6	5	5	8	0	0	0	0	0	0	5	0	1	4	2
1307	56	10	THIES Joey	6	t	0	0	-2	0	0	0	12	2	3	3	0	0	0	0	0
1308	56	11	HONG Joseph	6	f	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0
1309	56	18	DZINIC Aziz	6	f	0	0	0	2	0	0	0	0	0	0	3	0	0	0	0
1310	56	19	BOLLENDORFF Frank	6	f	0	0	-2	2	0	0	0	0	0	0	6	1	1	0	0
1311	56	55	WEIRIG Yann	6	f	12	4	9	10	2	0	0	0	0	0	21	0	1	9	3
1312	56	69	BESCH Tim	6	f	6	4	0	12	0	1	24	0	11	7	21	4	2	5	0
1313	56	77	BETTI Raphael	6	f	3	3	0	9	1	0	0	0	0	0	7	2	0	2	1
1314	56	1	NIZARD Gil	1	f	3	2	3	3	0	0	1	0	0	0	0	0	0	0	3
1315	56	3	WAGNER Victor	1	f	0	0	-1	9	0	0	0	0	0	0	1	0	1	0	0
1316	56	4	BIVER Antoine	1	f	5	2	1	6	1	0	0	0	0	0	12	2	1	3	2
1317	56	5	SOMMERHALTER Vince	1	f	3	2	-2	4	0	0	6	0	2	0	13	0	5	3	0
1318	56	7	FELLINGER Felix	1	f	6	1	-2	4	1	0	0	0	0	0	27	5	2	5	1
1319	56	10	HOFFMANN Maxime	1	f	5	0	1	9	1	0	0	0	0	0	11	3	0	5	0
1320	56	28	DARROSA JANKOVIC Ni	1	f	4	3	-2	4	2	0	14	3	4	2	13	1	0	3	1
1321	56	51	SANTOSI Peter	1	f	4	0	-7	11	1	0	34	4	13	8	22	5	1	4	0
1322	56	58	BARTH Frederic	1	t	0	0	0	0	0	0	13	0	8	8	0	0	0	0	0
\.


--
-- Data for Name: teams; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.teams (id, team_name) FROM stdin;
1	Escher VBC
2	VC Stroossen
3	VB Echternach
4	CHEV Diekirch
5	VC Fentange
6	VB Amber-Lenster
7	Volley Bartreng
8	VC Lorentzweiler
\.


--
-- Name: matches_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.matches_id_seq', 56, true);


--
-- Name: player_match_stats_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.player_match_stats_id_seq', 1322, true);


--
-- Name: teams_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.teams_id_seq', 8, true);


--
-- Name: matches matches_file_origin_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT matches_file_origin_key UNIQUE (file_origin);


--
-- Name: matches matches_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT matches_pkey PRIMARY KEY (id);


--
-- Name: player_match_stats player_match_stats_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.player_match_stats
    ADD CONSTRAINT player_match_stats_pkey PRIMARY KEY (id);


--
-- Name: teams teams_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_pkey PRIMARY KEY (id);


--
-- Name: teams teams_team_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_team_name_key UNIQUE (team_name);


--
-- Name: matches matches_away_team_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT matches_away_team_id_fkey FOREIGN KEY (away_team_id) REFERENCES public.teams(id);


--
-- Name: matches matches_home_team_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT matches_home_team_id_fkey FOREIGN KEY (home_team_id) REFERENCES public.teams(id);


--
-- Name: player_match_stats player_match_stats_match_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.player_match_stats
    ADD CONSTRAINT player_match_stats_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id) ON DELETE CASCADE;


--
-- Name: player_match_stats player_match_stats_team_played_for_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.player_match_stats
    ADD CONSTRAINT player_match_stats_team_played_for_id_fkey FOREIGN KEY (team_played_for_id) REFERENCES public.teams(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 7CwN5NNDHhdZ8dTBtF7h9RPgzUOM5hPDmrQmpR2kfldeasnBhtfOV09YUe5NVND

