# setup_db.py
import os
import logging
from dotenv import load_dotenv
import psycopg

# Load credentials from .env file
load_dotenv()

DB_NAME = os.getenv("DB_NAME")
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")

DB_CONN_STRING = f"dbname={DB_NAME} user={DB_USER} password={DB_PASSWORD} host={DB_HOST} port={DB_PORT}"

# --- LOGGING CONFIGURATION ---
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    handlers=[
        logging.FileHandler("database_setup.log", mode="a", encoding="utf-8"),
        logging.StreamHandler()
    ]
)

def initialize_database():
    logging.info("Connecting to PostgreSQL to initialize schema...")

    sql_schema = """
    -- Table 1: Unique list of teams
    CREATE TABLE IF NOT EXISTS teams (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        team_name VARCHAR UNIQUE
    );

    -- Table 2: Match metadata pointing to Teams
    CREATE TABLE IF NOT EXISTS matches (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        file_origin VARCHAR UNIQUE,
        match_date DATE,
        season VARCHAR,
        home_team_id INT REFERENCES teams(id),
        away_team_id INT REFERENCES teams(id)
    );

    -- Table 3: Individual player stats pointing to Matches and Teams
    CREATE TABLE IF NOT EXISTS player_match_stats (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        match_id INT REFERENCES matches(id) ON DELETE CASCADE,
        jersey INT,
        player_name VARCHAR,
        team_played_for_id INT REFERENCES teams(id),
        is_libero BOOLEAN,
        total_receptions INT,
        reception_errors INT
    );
    """

    try:
        with psycopg.connect(DB_CONN_STRING) as conn:
            with conn.cursor() as cur:
                cur.execute(sql_schema)
                conn.commit()
                logging.info("Database tables initialized successfully")

    except Exception as e:
        logging.critical("FAILED to initialize database tables.", exc_info=True)

if __name__ == "__main__":
    initialize_database()