
import os
import logging
from datetime import date
from typing import Optional
from dotenv import load_dotenv
from sqlalchemy import create_engine, String, Integer, Date, Boolean, ForeignKey, Identity
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Load credentials from .env file
load_dotenv()

DB_NAME = os.getenv("DB_NAME")
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")

# SQLAlchemy connection string uses a slightly different URI format
DB_CONN_STRING = f"postgresql+psycopg://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"

# --- LOGGING CONFIGURATION ---
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    handlers=[
        logging.FileHandler("database_setup.log", mode="a", encoding="utf-8"),
        logging.StreamHandler()
    ]
)

# --- DECLARED SCHEMA (ORM Models) ---

class Base(DeclarativeBase):
    """Abstract base class that maintains a catalog of tables and classes."""
    pass

class Team(Base):
    __tablename__ = "teams"

    # Identity() implements GENERATED BY DEFAULT AS IDENTITY
    id: Mapped[int] = mapped_column(Integer, Identity(), primary_key=True)
    team_name: Mapped[str] = mapped_column(String, unique=True, nullable=False)

class Match(Base):
    __tablename__ = "matches"

    id: Mapped[int] = mapped_column(Integer, Identity(), primary_key=True)
    file_origin: Mapped[str] = mapped_column(String, unique=True, nullable=False)
    match_date: Mapped[Optional[date]] = mapped_column(Date)
    season: Mapped[Optional[str]] = mapped_column(String)

    # Foreign keys pointing to teams table
    home_team_id: Mapped[Optional[int]] = mapped_column(ForeignKey("teams.id"))
    away_team_id: Mapped[Optional[int]] = mapped_column(ForeignKey("teams.id"))

class PlayerMatchStat(Base):
    __tablename__ = "player_match_stats"

    id: Mapped[int] = mapped_column(Integer, Identity(), primary_key=True)
    # ondelete="CASCADE" perfectly preserves your cascading behavior
    match_id: Mapped[int] = mapped_column(ForeignKey("matches.id", ondelete="CASCADE"))

    jersey: Mapped[Optional[int]] = mapped_column(Integer)
    player_name: Mapped[Optional[str]] = mapped_column(String)
    team_played_for_id: Mapped[Optional[int]] = mapped_column(ForeignKey("teams.id"))
    is_libero: Mapped[Optional[bool]] = mapped_column(Boolean)
    total_receptions: Mapped[Optional[int]] = mapped_column(Integer)
    reception_errors: Mapped[Optional[int]] = mapped_column(Integer)


# --- DATABASE INITIALIZATION TARGET ---

def initialize_database():
    logging.info("Connecting to PostgreSQL via SQLAlchemy to initialize schema...")

    try:
        # Create the engine (echo=False keeps logs clean, set to True to see raw SQL output)
        engine = create_engine(DB_CONN_STRING, echo=False)

        # Base.metadata.create_all inspects your models and safely executes
        # CREATE TABLE IF NOT EXISTS commands for all of them at once.
        Base.metadata.create_all(engine)

        logging.info("Database tables initialized successfully via SQLAlchemy!")

    except Exception as e:
        logging.critical("FAILED to initialize database tables.", exc_info=True)

if __name__ == "__main__":
    initialize_database()